
/* =========================
   DATA (FACTS)
========================= */
const facts = {
    Naruto: [
      "💀 Naruto was originally planned as a fox, not a human.",
      "💀 Naruto Uzumaki was feared before he was even understood.",
      "💀 Sasuke Uchiha leaving the village gave Naruto a true emotional goal.",
      "🧠 Itachi Uchiha lived as a criminal but died protecting peace. (Dark)",
      "🧠 Hinata Hyuga loved Naruto long before he became a hero. (Romantic)",
      "💀 Pain believed suffering was the only way to unite humanity.",
      "🧠 Naruto’s swing scene silently represents his loneliness. (Hidden)",
      "💀 Kakashi Hatake hides deep trauma behind humor and laziness.",
      "💀 Jiraiya died believing Naruto would change the world.",
      "🧠 The Akatsuki clouds symbolize bloodshed in endless wars. (Hidden)",
      "🧠 Obito Uchiha became evil because he couldn’t accept reality. (Dark)",
      "🧠 Naruto and Sasuke’s bond feels like a tragic love story. (Theory)",
      "💀 Sakura Haruno grows from weakest to one of the strongest",
      "💀 Naruto never gave up on Sasuke because he saw himself in him.",
      "💀 Gaara is Naruto’s mirror from a darker path.",
      "💀 Minato Namikaze trusted the future to his newborn son.",
      "🧠 Kushina Uzumaki’s love emotionally saved Naruto. (Romantic)",
      "💀 Naruto’s “talk no jutsu” is actually emotional intelligence.",
      "🧠 Madara Uchiha believed illusions are better than painful reality. (Theory)",
      "💀 Infinite Tsukuyomi is a world where no one suffers—but nothing is real.",
      "🧠 Shikamaru Nara hides genius behind laziness. (Hidden)",
      "💀 Neji Hyuga died proving destiny can be changed.",
      "🧠 Hinata Hyuga’s shyness shows pure, honest love. (Romantic)",
      "🧠 Itachi Uchiha planned his own death for Sasuke’s growth. (Dark)",
      "🧠 Kabuto Yakushi lost his identity due to manipulation. (Dark)",
      "💀 The Uchiha curse is emotional trauma, not just power.",
      "🧠 Naruto’s orange outfit symbolizes his need to be noticed. (Hidden)",
      "🧠 Tobi acting childish was a mask for pain.",
      "🖤 Zabuza Momochi cried only at the moment of death.",
      "💀 Haku’s love was pure loyalty, not romance.",
      "🖤 The ninja world uses children as soldiers.",
      "💀 Naruto forgives enemies because he understands them.",
      "💀 Kurama was evil only because he was treated like a weapon.",
      "😈 Sasuke Uchiha wanted to become a villain to unite the world.",
      "❤️ Hinata Hyuga risked her life confessing love during Pain’s attack.",
      "🖤 Kakashi Hatake lost everyone he loved before adulthood.",
      "😈 Naruto naming his son after Neji Hyuga would’ve been poetic.",
  
      "💀 Orochimaru represents fear of death and obsession with immortality.",
      "💀 Rock Lee proves hard work can rival talent.",
      "💀 Tsunade overcame trauma to lead the village.",
      "❤️ Love in Naruto is shown through sacrifice, not words.",
      "💀 Naruto and Sasuke losing arms symbolizes equality and balance.",
      "🖤 Madara Uchiha was defeated by betrayal, not strength.",
      "🧠 Black Zetsu manipulated history for centuries.",
      "😈 Kaguya Otsutsuki represents god-like isolation.",
      "💀 The war arc shows how quickly ideals collapse in reality.",
      "💀 Naruto’s smile hides years of emotional pain.",
  
      "💀 Iruka Umino was the first person to truly acknowledge Naruto.",
      "💀 Sasuke’s revenge was actually a search for meaning.",
      "❤️ Hinata Hyuga loved Naruto for who he was, not who he became.",
      "💀 The entire story is about choosing love over hatred.",
      "💀 Naruto Uzumaki smiled the most when he was hurting the most.",
      "💀 Sasuke Uchiha cutting bonds was his way of protecting himself from pain.",
      "🖤 Itachi Uchiha chose hatred over love so Sasuke could live in light.",
      "❤️ Hinata Hyuga loved Naruto even when he failed again and again.",
      "💀 Pain was once a hopeful child before war broke him.",
      "🧠 Naruto eating alone at Ichiraku shows his silent loneliness.",
  
      "😈 Kakashi Hatake never removed his mask because he hides more than his face.",
      "💀 Jiraiya wrote Naruto into his final book as the answer to peace.",
      "💀 Akatsuki members were all victims of the ninja system.",
      "🖤 Obito Uchiha saw the world as hell after losing Rin.",
      "💀 Naruto chasing Sasuke is like chasing a lost part of himself.",
      "❤️ Sakura Haruno loved Sasuke even knowing his darkness.",
      "💀 Gaara learned love only after meeting Naruto.",
      "🖤 Minato Namikaze sealed Kurama knowing his son would suffer.",
      "💀 Kushina Uzumaki’s last words shaped Naruto’s entire personality.",
      "😈 Naruto’s clones reflect his desire to never feel alone again.",
  
      "💀 Madara Uchiha wanted peace but forced it through illusion.",
      "🖤 Infinite Tsukuyomi traps people in their happiest dreams.",
      "💀 Shikamaru Nara matured instantly after losing Asuma.",
      "🖤 Asuma Sarutobi’s death taught responsibility through pain.",
      "💀 Neji Hyuga changed his fate the moment he chose to protect Naruto.",
      "❤️ Hinata Hyuga stepping in front of Pain was pure love, not courage.",
      "💀 Itachi Uchiha never stopped loving Sasuke even after death.",
      "🖤 Kabuto Yakushi became a villain because he never knew who he was.",
      "💀 The Sharingan evolves through emotional trauma.",
      "🧠 Naruto’s name comes from a ramen topping (narutomaki).",
  
      "💀 Tobi’s childish behavior hides his broken identity.",
      "💀 Zabuza Momochi died realizing he wasn’t emotionless after all.",
      "🖤 Haku lived only to be someone’s “tool.”",
      "😈 The ninja system rewards obedience over morality.",
      "💀 Naruto forgives because he understands pain, not because he forgets.",
      "💀 Kurama became kind only after being treated like a friend.",
      "😈 Sasuke Uchiha destroying the system was his twisted way of saving it.",
      "❤️ Hinata Hyuga saw Naruto as strong when everyone saw him weak.",
      "💀 Kakashi Hatake carries guilt for every loss he couldn’t prevent.",
      "🧠 Naruto’s chakra is huge because of both Uzumaki blood and Kurama.",
  
      "💀 Orochimaru fears death more than anything else.",
      "💀 Rock Lee proves effort can surpass natural talent.",
      "❤️ Tsunade avoided love because she feared losing it again.",
      "💀 Bonds in Naruto are stronger than power systems.",
      "💀 Naruto and Sasuke’s final fight ends with mutual understanding, not victory.",
      "🧠 Madara Uchiha was manipulated despite being nearly unstoppable.",
      "🧠 Black Zetsu secretly controlled events for centuries.",
      "😈 Kaguya Otsutsuki feared losing chakra, showing even gods feel fear.",
      "🖤 War in Naruto shows how quickly humanity breaks.",
      "💀 Naruto’s optimism is his strongest weapon.",
  
      "💀 Iruka Umino became Naruto’s emotional foundation.",
      "💀 Sasuke’s loneliness was deeper because he lost everything he loved.",
      "❤️ Hinata Hyuga loved Naruto without expecting anything in return.",
      "💀 Naruto’s story proves that pain can create either monsters or heroes.",
    ],
  
    "One Piece": [
      "🖤 Oda originally planned One Piece to last 5 years.",
      "🖤 Luffy was inspired by Goku.",
      "💀 Zoro once got lost in a straight line.",
      "🖤 Nico Robin was called a “demon child” at age 8 and had a bounty.",
      "🖤 Ohara was destroyed just to erase knowledge — not for crime.",
      "🖤 Brook spent 50 years alone with dead crewmates’ bodies.",
      "🖤 Big Mom literally ate her own friends as a child (implied).",
      "🖤 Kaido tried to kill himself multiple times but failed.",
      "🖤 Doflamingo killed his own father without hesitation.",
      "🖤 Celestial Dragons treat humans as slaves openly.",
      "🖤 Law watched his entire town die from disease and government neglect.",
      "🖤 Smile fruits can remove your ability to express sadness forever.",
      "🖤 Impel Down prisoners are tortured endlessly.",
      "💀 Freedom is more important than power in One Piece.",
      "💀 Pirates are shown more human than “justice” system.",
      "💀 Justice in One Piece is often corrupted.",
      "💀 Dreams never die — Blackbeard said it.",
      "💀 Every villain has a tragic backstory.",
      "💀 The sea represents true freedom.",
      "💀 Luffy never kills enemies — he destroys their dreams.",
      "💀 Straw Hats are all broken people finding purpose.",
      "💀 The world fears people who question truth.",
      "💀 One Piece is not just treasure — it’s truth, freedom, and history.",
      "😈 Shanks may know the entire truth of the world.",
      "😈 Blackbeard doesn’t sleep — possibly not fully human.",
      "😈 Zoro might have connections to Wano royalty.",
      "😈 The One Piece might be something that changes the world forever.",
      "😈 The Red Line might be destroyed at the end.",
      "😈 Luffy’s dream is still unknown even to fans.",
      "😈 The final war will be bigger than Marineford.",
      "😈 The government fears history more than pirates.",
      "😈 Vegapunk knows the truth but can’t reveal everything.",
      "😈 There may be a hidden traitor in major arcs (pattern theory).",
      "❤️ Sanji refuses to hit women because of Zeff’s teachings.",
      "❤️ Senor Pink dresses like a baby for his wife who’s in coma.",
      "❤️ Luffy rang the bell for Ace — his silent goodbye.",
      "❤️ Going Merry “died” and spoke its last words.",
      "❤️ Robin finally said “I want to live” after years of trauma.",
      "❤️ Nami asked Luffy for help — first time she trusted someone.",
      "❤️ Zoro took all of Luffy’s pain and said “Nothing happened.”",
      "❤️ Corazon died smiling to protect Law.",
      "❤️ Ace died protecting Luffy with a smile.",
      "❤️ Kuma protected Thousand Sunny for 2 years silently.",
      "🧠 Luffy’s fruit is not Gomu Gomu — it’s a mythical Zoan.",
      "🧠 Shanks stopped Kaido before Marineford (mystery how).",
      "🧠 Dragon (Luffy’s dad) is the most wanted man.",
      "🧠 Imu sits on the “empty throne” secretly ruling the world.",
      "🧠 The Will of D. is feared by the World Government.",
      "🧠 Blackbeard can have multiple devil fruits (unknown reason).",
      "🧠 Void Century is the biggest hidden truth.",
      "🧠 Joy Boy is connected to Luffy’s awakening.",
      "🧠 Ancient Weapons can destroy the world.",
      "🧠 Laugh Tale’s true story made Roger laugh.",
    ],
  
    "Demon Slayer": [
      "🖤Tanjiro has one of the strongest noses in anime.",
      "🖤Nezuko rarely speaks but shows deep emotion.",
      "💀 Tanjiro Kamado’s kindness is his greatest strength, not his weakness.",
      "🖤 Demons were once humans who lost themselves to despair.",
      "❤️ Nezuko Kamado fights her own nature to protect her brother.",
      "😈 Muzan Kibutsuji sees humans as disposable, not equal.",
      "🧠 Breathing techniques are human ways to mimic supernatural power.",
  
      "💀 Tanjiro smells emotions, not just scents.",
      "🖤 Becoming a demon erases your humanity piece by piece.",
      "❤️ Tanjiro’s love for Nezuko keeps her humanity alive.",
      "😈 Muzan fears the Sun more than anything.",
      "🧠 Each Hashira represents a different philosophy of strength.",
  
      "💀 Zenitsu Agatsuma’s fear hides incredible potential.",
      "🖤 Inosuke Hashibira’s aggression hides loneliness.",
      "❤️ Shinobu Kocho smiles to hide her hatred for demons.",
      "😈 Upper Moons are closer to Muzan than anyone else.",
      "🧠 Demon Blood Arts reflect a demon’s personality.",
  
      "💀 Tanjiro never loses his empathy, even for enemies.",
      "🖤 Many demons regret their actions only at death.",
      "❤️ Kanao Tsuyuri learns to feel through Tanjiro.",
      "😈 Muzan created demons to overcome death.",
      "🧠 The Demon Slayer Corps operates without official recognition.",
  
      "💀 Giyu Tomioka’s silence comes from survivor’s guilt.",
      "🖤 The Final Selection is designed to break weak spirits.",
      "❤️ Mitsuri Kanroji fights to find love and acceptance.",
      "😈 Demons grow stronger by consuming humans.",
      "🧠 Nichirin blades change color based on the user.",
  
      "💀 Rengoku Kyojuro’s death symbolizes unwavering resolve.",
      "🖤 Akaza rejects weakness because of his past trauma.",
      "❤️ Tanjiro treats every life as valuable.",
      "😈 Muzan eliminates anyone who disobeys him instantly.",
      "🧠 Total Concentration Breathing enhances physical limits.",
  
      "💀 Tanjiro’s journey is about protecting humanity, not revenge.",
      "🖤 Demons lose memories as they lose humanity.",
      "❤️ Nezuko chooses family over bloodlust.",
      "😈 Muzan hides among humans to survive.",
      "🧠 Hashira training pushes humans beyond natural limits.",
  
      "💀 Zenitsu becomes fearless only when unconscious.",
      "🖤 Inosuke wears a mask to hide vulnerability.",
      "❤️ Love in Demon Slayer is shown through sacrifice.",
      "😈 Upper Moon demons rarely get replaced.",
      "🧠 Wisteria flowers repel demons naturally.",
  
      "💀 Tanjiro’s scars represent growth through pain.",
      "🖤 The strongest demons were once the most broken humans.",
      "❤️ Shinobu’s kindness hides revenge.",
      "😈 Muzan’s cells can control other demons.",
      "🧠 Demon regeneration varies based on strength.",
  
      "💀 Every battle tests humanity vs survival instinct.",
      "🖤 Some demons beg for forgiveness too late.",
      "❤️ Kanao follows her heart because of Tanjiro.",
      "😈 Muzan fears being surpassed by his own creations.",
      "🧠 Swordsmiths play a crucial role in the Corps.",
  
      "💀 Tanjiro’s empathy is what makes him different from other slayers.",
      "🖤 Demons fear sunlight as absolute death.",
      "❤️ Nezuko protects humans despite her nature.",
      "😈 Muzan sees emotions as weakness.",
      "🧠 Breathing styles originate from Sun Breathing.",
  
      "💀 Tanjiro fights to save, not destroy.",
      "🖤 The Corps sacrifices countless lives for peace.",
      "❤️ Mitsuri’s strength comes from her emotions.",
      "😈 Demons cannot say Muzan’s name freely.",
      "🧠 Each breathing form has unique combat styles.",
  
      "💀 Giyu feels unworthy of being a Hashira.",
      "🖤 Sabito died helping others pass the test.",
      "❤️ Tanjiro honors even fallen enemies.",
      "😈 Muzan constantly evolves to avoid death.",
      "🧠 Demon Slayer marks increase power drastically.",
  
      "💀 Tanjiro’s determination never fades.",
      "🖤 Demons manipulate humans for survival.",
      "❤️ Family bonds drive the entire story.",
      "😈 Muzan values power over loyalty.",
      "🧠 The Corps has existed for generations.",
  
      "💀 Pain shapes every major character.",
      "🖤 Death is constant in the Demon Slayer world.",
      "❤️ Love gives characters purpose to fight.",
      "😈 Muzan fears the past catching up to him.",
      "🧠 Sun Breathing is the origin of all techniques.",
  
      "💀 Tanjiro represents hope in a cruel world.",
      "🖤 Demons are trapped between life and death.",
      "❤️ Nezuko’s humanity defies all rules.",
      "😈 Muzan’s existence is tied to fear of death.",
      "🧠 The strongest slayers combine skill with emotion.",
  
      "💀 Every victory comes with loss.",
      "🖤 Darkness defines the battlefield.",
      "❤️ Compassion is stronger than hatred.",
      "😈 Muzan’s empire is built on control.",
      "🧠 The balance of power is always shifting.",
    ],
  
    "Chained Soilder": [
      "💀 Yuuki Wakura’s worth is defined by how others use him, not who he is.",
      "🖤 The Mato world exists as a dangerous mirror to human society.",
      "💀 Kyouka Uzen’s leadership is built on control, not trust.",
      "❤️ Kyouka’s bond with Yuuki slowly turns from authority into affection.",
      "😈 Yuuki’s power symbolizes surrendering freedom for strength.",
  
      "🧠 The peaches granting powers only to women flips traditional power dynamics.",
      "💀 Yuuki’s chains represent both power and imprisonment.",
      "🖤 Every battle in Mato is a reminder that survival isn’t guaranteed.",
      "❤️ The rewards system hides emotional dependency beneath humor.",
      "😈 Yuuki may become stronger than the very system controlling him.",
  
      "💀 Kyouka sees Yuuki as a tool first, human second.",
      "🖤 The Mato monsters are born from distorted desires.",
      "🧠 The Anti-Demon Corps operates with hidden internal conflicts.",
      "❤️ Yuuki accepts pain if it means being needed.",
      "😈 The power structure hints at future rebellion against commanders.",
  
      "💀 Strength in Mato comes at the cost of humanity.",
      "🖤 Many characters hide trauma behind confidence.",
      "🧠 The rewards are psychological conditioning, not just fanservice.",
      "❤️ Yuuki’s loyalty grows into genuine emotional attachment.",
      "😈 Kyouka may lose control over Yuuki in the future.",
  
      "💀 Yuuki’s identity fades each time he transforms.",
      "🖤 Mato is a world where morality is blurred.",
      "🧠 Each squad reflects a different leadership philosophy.",
      "❤️ Kyouka begins to rely on Yuuki emotionally.",
      "😈 The hierarchy may collapse from within.",
  
      "💀 Power in Chained Soldier always demands a price.",
      "🖤 Characters often suppress fear to appear strong.",
      "🧠 The transformation system is a metaphor for exploitation.",
      "❤️ Yuuki’s kindness makes others protect him.",
      "😈 The monsters may have once been human.",
  
      "💀 Yuuki sacrifices dignity for purpose.",
      "🖤 The battlefield normalizes violence and suffering.",
      "🧠 Kyouka’s strict nature hides deep insecurity.",
      "❤️ Emotional bonds form through shared danger.",
      "😈 Yuuki could break the chain system entirely.",
  
      "💀 Dependence becomes a hidden weakness.",
      "🖤 Mato strips away individuality.",
      "🧠 Power imbalance defines every relationship.",
      "❤️ Care is often expressed through harsh actions.",
      "😈 Authority figures may become future antagonists.",
  
      "💀 Yuuki’s growth is tied to submission.",
      "🖤 Fear drives many decisions in battle.",
      "🧠 The Corps structure enforces obedience over freedom.",
      "❤️ Kyouka’s coldness softens only around Yuuki.",
      "😈 The system thrives on control, not justice.",
  
      "💀 Losing control is a constant risk of power.",
      "🖤 Survival often requires emotional detachment.",
      "🧠 Mato may symbolize inner human darkness.",
      "❤️ Yuuki’s presence changes those around him.",
      "😈 A rebellion arc is heavily foreshadowed.",
  
      "💀 Every transformation pushes Yuuki closer to losing himself.",
      "🖤 Violence is normalized as duty.",
      "🧠 The reward system reinforces loyalty.",
      "❤️ Bonds blur the line between duty and affection.",
      "😈 Power dynamics may reverse in the future.",
  
      "💀 Yuuki’s pain is hidden behind obedience.",
      "🖤 The strongest characters carry the heaviest burdens.",
      "🧠 Mato creatures reflect corrupted instincts.",
      "❤️ Emotional dependence grows subtly over time.",
      "😈 Kyouka’s authority may be challenged.",
  
      "💀 Power creates isolation.",
      "🖤 Trust is fragile in a system built on control.",
      "🧠 Each fight reveals deeper flaws in the system.",
      "❤️ Protection becomes a form of love.",
      "😈 Yuuki may surpass all commanders.",
  
      "💀 Identity is sacrificed for strength.",
      "🖤 The world rewards power, not morality.",
      "🧠 The Corps hides secrets from its own members.",
      "❤️ Affection grows through shared suffering.",
      "😈 Hidden truths about Mato may change everything.",
  
      "💀 Yuuki’s role questions the meaning of freedom.",
      "🖤 Darkness defines the world more than light.",
      "🧠 The system thrives on imbalance.",
      "❤️ Even control can turn into care.",
      "😈 The future may break all existing rules.",
  
      "💀 Strength comes with emotional cost.",
      "🖤 The line between monster and human is thin.",
      "🧠 Power structures mirror real-world hierarchies.",
      "❤️ Relationships evolve beyond initial intentions.",
      "😈 The origin of powers may be far darker than known.",
  
      "💀 Yuuki’s journey is about losing and rediscovering himself.",
      "🖤 The environment shapes morality.",
      "🧠 Control is disguised as protection.",
      "❤️ Emotional bonds drive character decisions.",
      "😈 The system may eventually collapse.",
    ],
  
    "Dragon Ball": [
      "💀 Goku was sent to Earth as a baby to conquer it but forgot his mission after hitting his head.",
      "🧠 His head injury erased his Saiyan aggression and made him kind-hearted.",
      "🖤 Goku’s original Saiyan name is Kakarot, given by his birth parents.",
      "💀 He was raised by Grandpa Gohan in complete isolation in the mountains.",
      "🖤 Goku accidentally killed Grandpa Gohan by transforming into a Great Ape.",
      "❤️ Despite that tragedy, he carried Gohan’s teachings with him forever.",
      "🧠 Goku’s tail in childhood gave him access to his hidden Saiyan power.",
      "😈 His Great Ape form was uncontrollable and purely destructive.",
      "💀 He lived a simple life hunting, fishing, and surviving alone.",
      "❤️ Meeting Bulma was the first time Goku experienced real friendship.",
  
      "🧠 Goku didn’t understand basic human concepts like money or relationships.",
      "💀 He trusted people easily because of his pure heart.",
      "🖤 Goku’s strength as a child already surpassed normal humans.",
      "❤️ He formed strong bonds quickly despite being socially unaware.",
      "😈 His Saiyan instincts showed up in his love for fighting.",
  
      "💀 Goku treated fighting as fun, not violence.",
      "🧠 He learned martial arts naturally without formal training at first.",
      "🖤 His childhood loneliness shaped his simple and honest personality.",
      "❤️ Grandpa Gohan’s influence made him value kindness over power.",
      "😈 His Saiyan biology pushed him to seek stronger opponents even as a kid.",
  
      "💀 Goku had no fear because he didn’t understand danger fully.",
      "🧠 His appetite as a child hinted at his Saiyan metabolism.",
      "🖤 He lived without knowing his real parents or origins.",
      "❤️ His innocence made people trust him instantly.",
      "😈 Even as a child, he defeated powerful enemies effortlessly.",
  
      "💀 Goku’s childhood was peaceful but built on hidden tragedy.",
      "🧠 His tail was his biggest weakness and strength at the same time.",
      "🖤 Removing his tail reduced his Saiyan abilities temporarily.",
      "❤️ He respected his master Roshi like a grandfather figure.",
      "😈 His early battles shaped his love for competition.",
  
      "💀 Goku never sought revenge for his losses.",
      "🧠 He improved through experience rather than strategy.",
      "🖤 His simplicity made him underestimate serious threats.",
      "❤️ His bond with Krillin started from rivalry and became brotherhood.",
      "😈 His Saiyan nature made him enjoy tough fights more than easy wins.",
  
      "💀 Goku’s pure heart allowed him to ride the Flying Nimbus.",
      "🧠 Nimbus rejects anyone with evil intentions instantly.",
      "🖤 His childhood enemies often became his allies later.",
      "❤️ Goku forgave even those who tried to kill him.",
      "😈 His growth attracted stronger enemies over time.",
  
      "💀 Goku’s childhood shaped him into a warrior without hatred.",
      "🧠 He learned techniques quickly due to natural talent.",
      "🖤 He didn’t understand death deeply until later.",
      "❤️ His kindness changed the lives of everyone he met.",
      "😈 His hidden potential was far beyond what others saw.",
    ],
  
    "One Punch Man": [
      "💀 Saitama’s boredom is the real curse of being unbeatable.",
      "🖤 He achieved ultimate power through a routine anyone can try, yet no one replicates.",
      "❤️ Saitama secretly wants a meaningful fight more than recognition.",
      "😈 The limiter theory suggests Saitama broke the natural laws of growth.",
      "🧠 His strength isn’t just physical—it defies logic itself.",
  
      "💀 Saitama lost his emotions as he gained power.",
      "🖤 Being the strongest isolated him more than weakness ever could.",
      "❤️ Genos sees Saitama as a hero, not just a teacher.",
      "😈 Saitama may have infinite potential, not a fixed limit.",
      "🧠 The Hero Association ranks don’t reflect true strength.",
  
      "💀 Saitama’s serious punch is still only a fraction of his power.",
      "🖤 Most villains die without ever understanding his strength.",
      "❤️ Saitama helps people without expecting gratitude.",
      "😈 His power might be a glitch in the universe itself.",
      "🧠 He trains the same way daily, showing absurd consistency.",
  
      "💀 Saitama forgot what fear feels like.",
      "🖤 His victories feel empty because there’s no struggle.",
      "❤️ He still values small human moments like sales and discounts.",
      "😈 Cosmic Garou reached near-god level but still couldn’t match him.",
      "🧠 Time travel was achieved through sheer physical ability.",
  
      "💀 Saitama can destroy planets casually but chooses not to.",
      "🖤 His strength removes the meaning of effort.",
      "❤️ King is admired as strong because of Saitama’s hidden actions.",
      "😈 God-level threats may exist beyond current understanding.",
      "🧠 His punches ignore durability and defenses completely.",
  
      "💀 Saitama’s existence breaks the story’s power scaling.",
      "🖤 Villains often have deeper motivations than heroes.",
      "❤️ Genos keeps upgrading just to catch up to Saitama.",
      "😈 The entity “God” may be watching Saitama closely.",
      "🧠 Saitama’s body adapts instantly to any threat.",
  
      "💀 He defeated Boros without going all out.",
      "🖤 Boros was one of the few who enjoyed fighting Saitama.",
      "❤️ Saitama respected Boros more than most enemies.",
      "😈 Boros hinted at beings even stronger than himself.",
      "🧠 Saitama survived attacks that could wipe out planets.",
  
      "💀 Saitama doesn’t care about fame or status.",
      "🖤 The world misunderstands true strength constantly.",
      "❤️ Mumen Rider represents true heroism without power.",
      "😈 Saitama may eventually fight a god-like being.",
      "🧠 His strength grows even after reaching “peak.”",
  
      "💀 Saitama’s blank expression hides existential emptiness.",
      "🖤 Winning every fight removes purpose.",
      "❤️ He still helps others because it feels right.",
      "😈 His power could collapse reality if uncontrolled.",
      "🧠 He can move faster than time itself.",
  
      "💀 Saitama never brags about his strength.",
      "🖤 Society values image over reality.",
      "❤️ Genos documents Saitama’s actions seriously.",
      "😈 The limiter concept suggests others could become like him.",
      "🧠 His strength doesn’t follow physics or logic.",
  
      "💀 Saitama’s punches end fights before they begin.",
      "🖤 Enemies rarely get closure against him.",
      "❤️ He treats allies casually but cares deeply.",
      "😈 Cosmic powers still fail against him.",
      "🧠 He can survive in space without effort.",
  
      "💀 Saitama became strong for fun, not purpose.",
      "🖤 That lack of purpose became his biggest struggle.",
      "❤️ His friendships slowly bring back his emotions.",
      "😈 The universe itself may not be able to limit him.",
      "🧠 His growth rate surpasses exponential logic.",
  
      "💀 He doesn’t train anymore but keeps improving.",
      "🖤 His existence makes other heroes question themselves.",
      "❤️ He inspires others unintentionally.",
      "😈 His power may be tied to breaking narrative rules.",
      "🧠 He can defeat enemies without trying techniques.",
  
      "💀 Saitama’s strength is both blessing and curse.",
      "🖤 No enemy can truly challenge him yet.",
      "❤️ He still believes a worthy opponent exists.",
      "😈 The story hints at future god-level conflicts.",
      "🧠 His abilities evolve beyond comprehension.",
  
      "💀 He represents the end of a hero’s journey.",
      "🖤 There’s nowhere left for him to grow emotionally.",
      "❤️ Yet he still chooses to be a hero every day.",
      "😈 His final opponent may redefine power itself.",
      "🧠 Saitama is less a character and more a concept of limitless strength.",
    ],
  
    "Attack on Titan": [
      "💀 Eren Yeager’s freedom was always an illusion shaped by fate.",
      "🖤 Titans were once humans stripped of their identity.",
      "❤️ Mikasa Ackerman’s love for Eren defines her entire existence.",
      "😈 The Attack Titan can see memories of future inheritors.",
      "🧠 The Walls were built using countless Colossal Titans.",
  
      "💀 Eren became the very thing he once swore to destroy.",
      "🖤 The world outside the walls is far crueler than inside.",
      "❤️ Armin Arlert believes understanding is stronger than violence.",
      "😈 Time in AOT is not linear but interconnected.",
      "🧠 Titan powers are connected through the “Paths.”",
  
      "💀 Freedom in AOT often comes at the cost of genocide.",
      "🖤 Eldians are hated for crimes they didn’t commit.",
      "❤️ Historia Reiss chooses her own identity over royal duty.",
      "😈 Eren manipulated events even in the past.",
      "🧠 All Subjects of Ymir are connected across time and space.",
  
      "💀 Every major victory in AOT comes with heavy loss.",
      "🖤 Humanity inside the walls lived in a controlled lie.",
      "❤️ Levi Ackerman shows care through actions, not words.",
      "😈 The Rumbling was planned long before it happened.",
      "🧠 Memories in AOT can influence decisions across generations.",
  
      "💀 Eren’s anger was rooted in helplessness as a child.",
      "🖤 Titans devour humans without reason or mercy.",
      "❤️ Sasha Blouse’s love for food symbolizes simple humanity.",
      "😈 The Founding Titan can alter reality itself.",
      "🧠 Royal blood unlocks the true potential of Titan powers.",
  
      "💀 The Survey Corps fight knowing they will likely die.",
      "🖤 War outside the walls is endless and political.",
      "❤️ Jean Kirstein grows from selfish to selfless.",
      "😈 Eren saw his own future and couldn’t escape it.",
      "🧠 Titan shifters inherit memories from previous users.",
  
      "💀 The basement reveal changed the entire meaning of the story.",
      "🖤 The real enemy was never just Titans.",
      "❤️ Connie Springer holds onto humanity despite loss.",
      "😈 Eren chose destruction believing it was the only path.",
      "🧠 The Coordinate connects all Eldians through one will.",
  
      "💀 Death is constant and unpredictable in AOT.",
      "🖤 Children are turned into weapons by war.",
      "❤️ Falco Grice wants to protect Gabi from becoming a monster.",
      "😈 Titan powers are passed through consumption.",
      "🧠 The 13-year curse limits Titan shifters’ lifespan.",
  
      "💀 Eren sacrificed his humanity for his idea of freedom.",
      "🖤 Marley uses Eldians as tools of war.",
      "❤️ Mikasa’s scarf represents emotional safety and love.",
      "😈 Ymir Fritz remained a slave even with god-like power.",
      "🧠 Paths exist outside normal time and space.",
  
      "💀 The Rumbling shows humanity’s darkest potential.",
      "🖤 Revenge fuels endless cycles of violence.",
      "❤️ Armin tries to resolve conflict without destruction.",
      "😈 Eren became both hero and villain simultaneously.",
      "🧠 The story blurs the line between right and wrong.",
  
      "💀 No side in AOT is completely innocent.",
      "🖤 War forces people to abandon morality.",
      "❤️ Historia protects children from the same fate she had.",
      "😈 Eren influenced his father’s actions in the past.",
      "🧠 The Attack Titan embodies the desire for freedom.",
  
      "💀 The ending shows that conflict never truly ends.",
      "🖤 Humanity repeats its mistakes across generations.",
      "❤️ Mikasa’s final choice defines her independence.",
      "😈 The future was always predetermined.",
      "🧠 AOT explores deterministic vs free will philosophy.",
  
      "💀 Eren’s smile at the end hides deep sadness.",
      "🖤 Entire civilizations were wiped out in moments.",
      "❤️ Love persists even in a world of war.",
      "😈 The Rumbling was both salvation and destruction.",
      "🧠 Power corrupts even the purest intentions.",
  
      "💀 The story begins and ends with Eren’s perspective.",
      "🖤 Fear is the driving force behind hatred.",
      "❤️ Bonds between characters keep them human.",
      "😈 The Titans were tools of oppression, not evolution.",
      "🧠 Knowledge changes the nature of conflict.",
  
      "💀 Freedom in AOT is always paid with sacrifice.",
      "🖤 Humanity is capable of greater cruelty than Titans.",
      "❤️ Mikasa loved Eren beyond reason or logic.",
      "😈 Eren’s plan reshaped the entire world.",
      "🧠 The story is a reflection of real-world war and cycles.",
  
      "💀 In the end, Eren became a prisoner of his own destiny.",
      "🖤 The world outside the walls was never truly free.",
      "❤️ Hope exists even after devastation.",
      "😈 The final outcome was inevitable from the beginning.",
      "🧠 AOT is less about Titans and more about human nature.",
    ],
  
    "Food Wars": [
      "💀 Soma Yukihira treats cooking like a battlefield, not just a skill.",
      "🖤 Failure is more common than success at Totsuki Academy.",
      "❤️ Soma cooks to make people smile, not to prove superiority.",
      "😈 Shokugeki battles can destroy reputations instantly.",
      "🧠 Cooking in Food Wars blends science with creativity.",
  
      "💀 Soma’s strength comes from constant experimentation.",
      "🖤 Elite Ten hold absolute power over the academy.",
      "❤️ Erina Nakiri hides admiration behind harsh criticism.",
      "😈 Judges’ decisions can change a chef’s entire future.",
      "🧠 Flavor combinations are treated like strategic weapons.",
  
      "💀 Soma embraces failure as a learning tool.",
      "🖤 Many students quit under extreme pressure.",
      "❤️ Megumi Tadokoro grows through support and belief.",
      "😈 Cooking battles are psychological as well as physical.",
      "🧠 Each dish tells a story about the chef.",
  
      "💀 Soma challenges opponents stronger than himself fearlessly.",
      "🖤 The academy system is built to eliminate the weak.",
      "❤️ Joichiro Yukihira inspired Soma’s passion for cooking.",
      "😈 Chefs manipulate senses to overwhelm judges.",
      "🧠 Presentation is as important as taste.",
  
      "💀 Soma’s creativity breaks traditional cooking rules.",
      "🖤 Expulsion is a constant threat for students.",
      "❤️ Erina’s “God Tongue” isolates her emotionally.",
      "😈 Some chefs rely on intimidation to win.",
      "🧠 Cooking techniques are explained with scientific precision.",
  
      "💀 Soma never loses his confidence after defeat.",
      "🖤 Pressure at Totsuki can break even talented chefs.",
      "❤️ Friendships form through rivalry.",
      "😈 Cooking battles often reflect personal conflicts.",
      "🧠 Ingredients are chosen like tactical decisions.",
  
      "💀 Soma’s dishes often look simple but surprise everyone.",
      "🖤 The academy values results over effort.",
      "❤️ Megumi’s kindness becomes her strength.",
      "😈 Elite chefs control the academy’s future.",
      "🧠 Cooking evolves through experimentation.",
  
      "💀 Soma challenges authority without hesitation.",
      "🖤 Fear of failure controls many students.",
      "❤️ Erina slowly learns to trust others.",
      "😈 Power struggles exist beyond the kitchen.",
      "🧠 Culinary skills reflect personality.",
  
      "💀 Cooking battles test mental endurance.",
      "🖤 Losing a Shokugeki can end a career.",
      "❤️ Soma respects opponents regardless of outcome.",
      "😈 Some chefs cook to dominate, not create.",
      "🧠 Heat control and timing are critical.",
  
      "💀 Soma’s unpredictability is his greatest weapon.",
      "🖤 The system rewards perfection, not growth.",
      "❤️ Bonds grow stronger through competition.",
      "😈 Cooking becomes a form of warfare.",
      "🧠 Flavor layering creates emotional impact.",
  
      "💀 Soma thrives under pressure.",
      "🖤 Many chefs hide insecurity behind arrogance.",
      "❤️ Erina’s journey is about emotional freedom.",
      "😈 Judges can be manipulated psychologically.",
      "🧠 Texture contrasts enhance experience.",
  
      "💀 Soma’s resilience defines his growth.",
      "🖤 Failure can destroy confidence instantly.",
      "❤️ Team cooking builds trust.",
      "😈 Some battles are decided before they begin.",
      "🧠 Aroma plays a major role in perception.",
  
      "💀 Cooking reflects identity.",
      "🖤 Competition creates constant tension.",
      "❤️ Soma values people over victory.",
      "😈 Elite Ten shape the academy’s direction.",
      "🧠 Culinary innovation drives success.",
  
      "💀 Every dish is a risk.",
      "🖤 Pressure forces chefs to evolve or quit.",
      "❤️ Relationships deepen through shared struggle.",
      "😈 Power dynamics influence outcomes.",
      "🧠 Cooking blends art and science.",
  
      "💀 Soma’s journey is about growth, not winning.",
      "🖤 The academy creates both legends and failures.",
      "❤️ Passion fuels every great dish.",
      "😈 High stakes make every battle intense.",
      "🧠 True skill comes from understanding fundamentals.",
  
      "💀 Cooking is survival in Totsuki.",
      "🖤 Only the strongest endure the system.",
      "❤️ Food connects people emotionally.",
      "😈 Victory often comes with sacrifice.",
      "🧠 Mastery requires both logic and instinct.",
  
      "💀 Soma never stops improving.",
      "🖤 Competition never truly ends.",
      "❤️ Cooking expresses emotions without words.",
      "😈 The system pushes chefs beyond limits.",
      "🧠 Great chefs adapt to any situation.",
    ],
  
    Bleach: [
      "💀 Ichigo Kurosaki was born with powers even before becoming a Soul Reaper.",
      "🖤 Hollows are souls consumed by loneliness and regret.",
      "❤️ Orihime Inoue’s powers come from her desire to protect others.",
      "😈 Aizen Sosuke manipulated everyone while appearing loyal.",
      "🧠 Zanpakuto spirits reflect their wielder’s true self.",
  
      "💀 Ichigo’s strength comes from multiple conflicting powers.",
      "🖤 Soul Society hides dark truths behind order.",
      "❤️ Rukia Kuchiki changed Ichigo’s entire destiny.",
      "😈 Aizen planned events years before they happened.",
      "🧠 Bankai represents mastery of one’s soul.",
  
      "💀 Ichigo is part human, Soul Reaper, Hollow, and Quincy.",
      "🖤 Hollows lose their hearts before becoming monsters.",
      "❤️ Ichigo fights to protect, not to conquer.",
      "😈 The Hogyoku grants desires but twists them.",
      "🧠 Spiritual pressure determines strength levels.",
  
      "💀 Ichigo’s inner Hollow represents his hidden instincts.",
      "🖤 Many Soul Reapers follow rules over morality.",
      "❤️ Orihime’s kindness affects even enemies.",
      "😈 Aizen sees himself above all beings.",
      "🧠 Each Zanpakuto has a unique ability.",
  
      "💀 Ichigo constantly struggles with his own identity.",
      "🖤 The Soul Society executes its own members.",
      "❤️ Renji Abarai grows stronger through loyalty.",
      "😈 Espada represent different aspects of death.",
      "🧠 Hollow masks increase power temporarily.",
  
      "💀 Ichigo’s growth is tied to understanding himself.",
      "🖤 Hueco Mundo is a world of endless despair.",
      "❤️ Rukia’s bond with Ichigo is deeper than friendship.",
      "😈 Ulquiorra represents emptiness and nihilism.",
      "🧠 Quincy powers come from absorbing reishi.",
  
      "💀 Ichigo never fights for pride.",
      "🖤 Many villains were victims before becoming enemies.",
      "❤️ Orihime rejects violence despite her power.",
      "😈 Aizen wanted to overthrow the Soul King.",
      "🧠 Soul King maintains balance between worlds.",
  
      "💀 Ichigo’s power scares even allies.",
      "🖤 Hollows evolve into stronger forms through consumption.",
      "❤️ Friendship drives many battles.",
      "😈 Yhwach can see and alter the future.",
      "🧠 Quincy abilities counter Soul Reapers.",
  
      "💀 Ichigo’s determination surpasses logic.",
      "🖤 War between Quincy and Soul Reapers is inevitable.",
      "❤️ Love is shown through protection.",
      "😈 Sternritter abilities defy natural laws.",
      "🧠 Spiritual energy shapes reality.",
  
      "💀 Ichigo’s Bankai reflects his speed and power.",
      "🖤 Many characters suffer in silence.",
      "❤️ Orihime heals rather than destroys.",
      "😈 Yhwach sees himself as destiny.",
      "🧠 Reishi forms the basis of all spiritual matter.",
  
      "💀 Ichigo loses power multiple times but regains it stronger.",
      "🖤 Betrayal is common in Bleach.",
      "❤️ Rukia grows into a strong leader.",
      "😈 Aizen never truly loses his composure.",
      "🧠 Training in Bleach often involves inner battles.",
  
      "💀 Ichigo protects both worlds equally.",
      "🖤 The balance of souls is fragile.",
      "❤️ Bonds give characters strength.",
      "😈 Villains often believe they are right.",
      "🧠 Techniques evolve with experience.",
  
      "💀 Ichigo represents balance between opposing forces.",
      "🖤 Darkness exists in every soul.",
      "❤️ Compassion changes outcomes.",
      "😈 Power corrupts those who seek control.",
      "🧠 True strength comes from self-acceptance.",
  
      "💀 Every arc challenges Ichigo’s identity.",
      "🖤 Death is a constant theme.",
      "❤️ Relationships shape decisions.",
      "😈 The final war changes everything.",
      "🧠 Knowledge of power determines victory.",
  
      "💀 Ichigo never stops moving forward.",
      "🖤 The line between hero and villain is blurred.",
      "❤️ Protecting others defines true strength.",
      "😈 Fate plays a major role in events.",
      "🧠 Bleach explores the nature of the soul itself.",
    ],
  
    "Spy x Family": [
      "💀 Loid Forger lives a fake life so others can live real ones.",
      "🖤 His identity is built on lies layered over lies.",
      "❤️ Yor Forger hides genuine love behind her awkwardness.",
      "😈 Operation Strix could collapse if a single truth is revealed.",
      "🧠 Anya Forger’s telepathy gives her power no one understands.",
  
      "💀 Loid sacrificed his true self for peace.",
      "🖤 Being a spy means never forming real attachments.",
      "❤️ Anya just wants a happy family, not missions.",
      "😈 Yor lives as both a killer and a caretaker.",
      "🧠 Anya reads minds but can’t control what she hears.",
  
      "💀 Loid constantly questions his own identity.",
      "🖤 The world is built on political tension and hidden war.",
      "❤️ Yor learns love through small daily moments.",
      "😈 Twilight is feared but never truly known.",
      "🧠 Anya’s childish behavior hides sharp awareness.",
  
      "💀 Loid’s perfection hides emotional emptiness.",
      "🖤 Trust is dangerous in the world of spies.",
      "❤️ The Forger family bond grows despite being fake.",
      "😈 One mistake could expose everything.",
      "🧠 Anya often manipulates situations using telepathy.",
  
      "💀 Loid doesn’t realize he’s becoming a real father.",
      "🖤 Yor’s assassin life isolates her from normal society.",
      "❤️ Anya connects the family emotionally.",
      "😈 Secret identities create constant tension.",
      "🧠 Every mission is carefully calculated.",
  
      "💀 Loid’s childhood trauma drives his mission for peace.",
      "🖤 War shaped his belief that lies can save lives.",
      "❤️ Yor protects her family with genuine care.",
      "😈 Assassination is treated as routine work.",
      "🧠 Intelligence gathering is Loid’s greatest weapon.",
  
      "💀 Anya understands more than adults realize.",
      "🖤 Children are affected by war indirectly.",
      "❤️ Her innocence brings warmth to dark situations.",
      "😈 The secret police monitor everything silently.",
      "🧠 Loid predicts outcomes before acting.",
  
      "💀 Loid suppresses emotions to stay effective.",
      "🖤 Yor hides her fears behind strength.",
      "❤️ Their marriage slowly becomes real.",
      "😈 Lies are necessary for survival.",
      "🧠 Anya’s reactions often change outcomes unexpectedly.",
  
      "💀 Loid fears emotional attachment.",
      "🖤 Being discovered means death or worse.",
      "❤️ Anya values simple happiness over success.",
      "😈 Yor’s strength makes her both protector and threat.",
      "🧠 Strategy defines success in espionage.",
  
      "💀 Loid’s calmness hides constant pressure.",
      "🖤 The political world is filled with manipulation.",
      "❤️ Family dinners become moments of real connection.",
      "😈 Secrets build invisible walls between characters.",
      "🧠 Anya uses humor to cope with stress.",
  
      "💀 Loid’s mission is endless.",
      "🖤 Peace is fragile and temporary.",
      "❤️ Yor learns what normal life feels like.",
      "😈 Twilight’s identity must never be exposed.",
      "🧠 Anya adapts quickly to situations.",
  
      "💀 Loid questions if his mission is worth the cost.",
      "🖤 War creates people like Twilight and Yor.",
      "❤️ The family begins to depend on each other.",
      "😈 Danger exists even in peaceful settings.",
      "🧠 Observation is key to survival.",
  
      "💀 Loid hides loneliness behind professionalism.",
      "🖤 Yor’s past shaped her into a weapon.",
      "❤️ Anya brings emotional balance to the family.",
      "😈 Every character hides something important.",
      "🧠 Planning is more powerful than strength.",
  
      "💀 Loid’s life is built on temporary identities.",
      "🖤 Truth is more dangerous than lies.",
      "❤️ The fake family becomes emotionally real.",
      "😈 The mission could end at any moment.",
      "🧠 Intelligence outweighs brute force.",
  
      "💀 Loid doesn’t know what real happiness feels like.",
      "🖤 Yor fears losing the only family she has.",
      "❤️ Anya wants to keep everyone together.",
      "😈 The world rewards deception.",
      "🧠 Even small actions affect big outcomes.",
  
      "💀 Loid slowly becomes what he pretends to be.",
      "🖤 The line between real and fake disappears.",
      "❤️ Love grows without anyone realizing it.",
      "😈 Secrets may eventually destroy everything.",
      "🧠 Spy work is about controlling information.",
  
      "💀 The greatest conflict is internal, not external.",
      "🖤 Every character lives a double life.",
      "❤️ Family is formed through choice, not blood.",
      "😈 Truth could shatter their bond instantly.",
      "🧠 The story blends strategy with emotion.",
    ],
  
    "Sakamoto Days": [
      "💀 Taro Sakamoto gave up the underworld’s deadliest life for a normal family.",
      "🖤 His past as a legendary hitman still haunts every step of his peaceful life.",
      "❤️ Sakamoto chose love over power, something few assassins ever do.",
      "😈 The assassin world refuses to let him retire peacefully.",
      "🧠 Sakamoto’s instincts remain sharp even in his relaxed state.",
  
      "💀 His current appearance hides his terrifying past strength.",
      "🖤 Every enemy sees him as a legend they must surpass or eliminate.",
      "❤️ His family is the only reason he holds back his true power.",
      "😈 Killing is forbidden in his new life, but violence still follows him.",
      "🧠 He can analyze threats instantly without visible effort.",
  
      "💀 Sakamoto proves strength doesn’t disappear—it adapts.",
      "🖤 The assassin world is ruthless and unforgiving.",
      "❤️ He protects his family with absolute devotion.",
      "😈 Old enemies constantly test his limits.",
      "🧠 His combat style blends creativity with efficiency.",
  
      "💀 Even weakened, Sakamoto outclasses most fighters.",
      "🖤 Violence is normalized in his past world.",
      "❤️ His wife represents the peaceful life he chose.",
      "😈 Breaking his no-kill rule would change everything.",
      "🧠 He uses everyday objects as deadly weapons.",
  
      "💀 Sakamoto’s calmness hides overwhelming power.",
      "🖤 His past actions still define how others see him.",
      "❤️ Family moments ground him emotionally.",
      "😈 The assassin network constantly hunts him.",
      "🧠 His experience makes him unpredictable.",
  
      "💀 Sakamoto’s strength comes from mastery, not brute force.",
      "🖤 The line between good and evil is blurred in his world.",
      "❤️ He values simple happiness over dominance.",
      "😈 Assassins operate with their own twisted codes.",
      "🧠 Strategy often wins over raw strength.",
  
      "💀 He suppresses his killer instincts to stay human.",
      "🖤 Many assassins live without purpose beyond killing.",
      "❤️ His kindness contrasts his deadly skills.",
      "😈 The past always finds a way back.",
      "🧠 His reflexes are near superhuman.",
  
      "💀 Sakamoto’s legend is bigger than his current self.",
      "🖤 Fear surrounds his name in the underworld.",
      "❤️ His family sees him as just a normal man.",
      "😈 Enemies underestimate him due to his appearance.",
      "🧠 He turns any environment into an advantage.",
  
      "💀 He balances violence and peace constantly.",
      "🖤 The assassin world thrives on chaos.",
      "❤️ Protecting loved ones drives his actions.",
      "😈 Former allies can become deadly enemies.",
      "🧠 His mind works faster than most opponents.",
  
      "💀 Sakamoto never truly escapes his past.",
      "🖤 Danger follows him everywhere.",
      "❤️ His family gives him a reason to fight differently.",
      "😈 Rules exist but are often broken.",
      "🧠 He predicts enemy moves effortlessly.",
  
      "💀 His restraint is his greatest strength.",
      "🖤 Killing becomes a habit for many assassins.",
      "❤️ Love reshaped his entire life.",
      "😈 The assassin hierarchy is constantly shifting.",
      "🧠 He adapts to any fighting style.",
  
      "💀 Sakamoto’s presence alone intimidates enemies.",
      "🖤 Trust is rare in the assassin world.",
      "❤️ His bond with his wife defines his humanity.",
      "😈 Hidden threats exist everywhere.",
      "🧠 His skills never fade, only evolve.",
  
      "💀 He proves peace requires more strength than violence.",
      "🖤 The world sees him as a weapon, not a man.",
      "❤️ His family sees his true self.",
      "😈 Enemies seek glory by defeating him.",
      "🧠 He uses intelligence over aggression.",
  
      "💀 Sakamoto fights to protect, not dominate.",
      "🖤 The past leaves scars that never fade.",
      "❤️ Everyday life becomes meaningful to him.",
      "😈 Conflict is unavoidable in his world.",
      "🧠 He masters every situation quickly.",
  
      "💀 His dual life creates constant tension.",
      "🖤 The assassin world never forgets.",
      "❤️ Love gives him purpose beyond survival.",
      "😈 One mistake could cost everything.",
      "🧠 Awareness is his greatest weapon.",
  
      "💀 Sakamoto embodies strength with restraint.",
      "🖤 Violence shaped his identity but doesn’t define him now.",
      "❤️ His family represents hope and change.",
      "😈 The future may force him to return to his old self.",
      "🧠 He is always thinking several steps ahead.",
  
      "💀 His story is about choosing peace over chaos.",
      "🖤 Darkness still surrounds his life.",
      "❤️ Bonds keep him grounded.",
      "😈 The assassin world is always watching.",
      "🧠 True strength lies in control, not destruction.",
    ],
  
    "Jujutsu Kaisen": [
      "💀 Yuji Itadori carries death inside him while choosing to save lives.",
      "🖤 Curses are born from human fear and negative emotions.",
      "❤️ Yuji values every life, even when the world doesn’t.",
      "😈 Ryomen Sukuna exists as pure selfish destruction.",
      "🧠 Cursed energy flows from negative human emotions.",
  
      "💀 Yuji’s kindness makes his suffering heavier.",
      "🖤 Sorcerers are forced to face death constantly.",
      "❤️ Megumi Fushiguro saves people he personally believes deserve it.",
      "😈 Sukuna sees humans as insects, not equals.",
      "🧠 Domain Expansion guarantees a hit within its space.",
  
      "💀 Yuji becomes executioner and protector at the same time.",
      "🖤 The jujutsu world sacrifices youth for balance.",
      "❤️ Nobara Kugisaki fights with pride and self-identity.",
      "😈 Mahito manipulates souls without remorse.",
      "🧠 Each sorcerer has a unique cursed technique.",
  
      "💀 Yuji is forced to kill cursed humans he wanted to save.",
      "🖤 Death in Jujutsu Kaisen is sudden and brutal.",
      "❤️ Gojo Satoru cares deeply despite his carefree attitude.",
      "😈 Sukuna waits patiently to take control.",
      "🧠 Reverse cursed technique heals using positive energy.",
  
      "💀 Yuji’s strength comes with emotional consequences.",
      "🖤 Curses reflect humanity’s darkest thoughts.",
      "❤️ Junpei’s story shows how fragile kindness is.",
      "😈 Mahito evolves through cruelty and experimentation.",
      "🧠 Black Flash amplifies power through perfect timing.",
  
      "💀 Gojo’s power isolates him from others.",
      "🖤 Being the strongest means being alone.",
      "❤️ Yuji fights to give people a proper death.",
      "😈 Sukuna enjoys chaos and suffering.",
      "🧠 Limitless technique manipulates space itself.",
  
      "💀 Yuji loses pieces of himself with every fight.",
      "🖤 Sorcerers often die without recognition.",
      "❤️ Friendship keeps characters human.",
      "😈 The cursed world thrives on imbalance.",
      "🧠 Six Eyes allows precise cursed energy control.",
  
      "💀 Megumi struggles between logic and emotion.",
      "🖤 The system uses sorcerers as tools.",
      "❤️ Nobara refuses to lose her identity.",
      "😈 Sukuna’s power grows with each finger consumed.",
      "🧠 Shikigami reflect the user’s strength.",
  
      "💀 Yuji’s journey is about accepting unavoidable death.",
      "🖤 Many villains were shaped by suffering.",
      "❤️ Gojo protects the next generation.",
      "😈 Mahito represents the fear of human souls.",
      "🧠 Cursed techniques evolve through experience.",
  
      "💀 Every mission risks death.",
      "🖤 The jujutsu world hides harsh truths.",
      "❤️ Bonds form through shared trauma.",
      "😈 Sukuna has his own hidden goals.",
      "🧠 Barriers control space and conditions.",
  
      "💀 Yuji’s optimism is constantly tested.",
      "🖤 Loss is inevitable for sorcerers.",
      "❤️ Even small kindness matters.",
      "😈 Curses grow stronger with fear.",
      "🧠 Energy control defines combat ability.",
  
      "💀 Gojo carries the burden of being unmatched.",
      "🖤 Power creates isolation.",
      "❤️ Yuji refuses to give up on people.",
      "😈 Sukuna’s presence distorts reality.",
      "🧠 Techniques require deep understanding.",
  
      "💀 Yuji is both hero and vessel of destruction.",
      "🖤 Humanity creates its own monsters.",
      "❤️ Protecting others defines strength.",
      "😈 Villains often mirror heroes.",
      "🧠 Knowledge of curses is key to survival.",
  
      "💀 Death teaches harsh lessons.",
      "🖤 Fear drives the creation of curses.",
      "❤️ Characters fight for personal reasons.",
      "😈 Sukuna represents ultimate selfishness.",
      "🧠 Domains reflect inner psyche.",
  
      "💀 Yuji continues despite overwhelming odds.",
      "🖤 The line between human and curse blurs.",
      "❤️ Compassion exists even in darkness.",
      "😈 The future holds greater threats.",
      "🧠 Jujutsu Kaisen explores balance between life and death.",
  
      "💀 Pain shapes every sorcerer.",
      "🖤 Darkness is unavoidable.",
      "❤️ Hope exists through connection.",
      "😈 Power alone cannot solve everything.",
      "🧠 True strength comes from understanding oneself.",
  
      "💀 Yuji’s story is about choosing humanity over despair.",
      "🖤 The world is built on hidden suffering.",
      "❤️ Bonds give meaning to sacrifice.",
      "😈 Sukuna may become the greatest threat ever.",
      "🧠 The series blends philosophy with action.",
    ],
  
    "Chainsaw Man": [
      "💀 Denji’s dream is painfully simple: food, shelter, and affection.",
      "🖤 Devils are born from human fears, growing stronger with belief.",
      "❤️ Pochita represents unconditional love in a cruel world.",
      "😈 Makima controls others through invisible dominance.",
      "🧠 Contracts with devils always demand a price.",
  
      "💀 Denji lived in poverty so extreme it shaped his desires.",
      "🖤 The world treats devil hunters as disposable tools.",
      "❤️ Denji values small happiness more than big dreams.",
      "😈 Makima’s kindness hides terrifying intentions.",
      "🧠 Each devil embodies a specific human fear.",
  
      "💀 Denji sells parts of his body just to survive.",
      "🖤 Death is constant and meaningless in this world.",
      "❤️ Power learns human connection through Denji.",
      "😈 The Gun Devil represents fear of modern violence.",
      "🧠 Fear determines a devil’s strength level.",
  
      "💀 Denji becomes Chainsaw Man by merging with Pochita.",
      "🖤 Humanity depends on monsters to fight monsters.",
      "❤️ Aki Hayakawa sacrifices everything for revenge.",
      "😈 Makima manipulates emotions as weapons.",
      "🧠 Devils can regenerate using blood.",
  
      "💀 Denji confuses love with basic human needs.",
      "🖤 The system exploits devil hunters without care.",
      "❤️ Aki slowly forms a real family with Denji and Power.",
      "😈 Control is Makima’s true nature.",
      "🧠 Hybrid devils combine human and devil traits.",
  
      "💀 Denji’s innocence makes him vulnerable.",
      "🖤 Violence is normalized in everyday life.",
      "❤️ Power’s bond with Denji changes her personality.",
      "😈 Makima sees people as tools, not individuals.",
      "🧠 Some devils fear Chainsaw Man himself.",
  
      "💀 Denji’s happiness is always temporary.",
      "🖤 Every character carries trauma.",
      "❤️ Found family becomes central to survival.",
      "😈 Devils fear being erased by Chainsaw Man.",
      "🧠 Erased devils are forgotten from existence.",
  
      "💀 Denji fights without deeper purpose at first.",
      "🖤 The world offers no fairness or justice.",
      "❤️ Aki’s relationships soften his revenge-driven heart.",
      "😈 Makima seeks control over existence itself.",
      "🧠 Devil names define their power.",
  
      "💀 Denji’s life improves but never becomes easy.",
      "🖤 Loss happens suddenly and without warning.",
      "❤️ Small moments create real happiness.",
      "😈 Makima’s presence creates silent fear.",
      "🧠 Contracts can take lifespan or body parts.",
  
      "💀 Denji grows emotionally through suffering.",
      "🖤 Trust is dangerous in this world.",
      "❤️ Power learns loyalty through Denji.",
      "😈 Devils exploit human weaknesses.",
      "🧠 Blood is a key source of power.",
  
      "💀 Denji questions what happiness truly means.",
      "🖤 The strongest often suffer the most.",
      "❤️ Aki values his new family more than revenge.",
      "😈 Makima controls events behind the scenes.",
      "🧠 Hybrids can revive repeatedly.",
  
      "💀 Denji’s dreams evolve over time.",
      "🖤 Humanity creates the fears that create devils.",
      "❤️ Relationships give meaning to survival.",
      "😈 Makima’s plan spans beyond simple control.",
      "🧠 Devils return after death in cycles.",
  
      "💀 Denji loses parts of himself emotionally.",
      "🖤 The world punishes innocence.",
      "❤️ Love exists even in chaos.",
      "😈 Makima represents absolute control.",
      "🧠 Fear can reshape reality itself.",
  
      "💀 Denji keeps moving forward despite everything.",
      "🖤 Death has little warning or buildup.",
      "❤️ Bonds are fragile but meaningful.",
      "😈 Devils act on instinct and desire.",
      "🧠 Knowledge of devils ensures survival.",
  
      "💀 Denji represents survival at its rawest form.",
      "🖤 Darkness defines the environment.",
      "❤️ Kindness is rare but powerful.",
      "😈 Makima’s influence extends everywhere.",
      "🧠 Power systems revolve around fear and contracts.",
  
      "💀 Every victory comes with loss.",
      "🖤 The line between human and monster blurs.",
      "❤️ Denji values connection more over time.",
      "😈 True villains hide behind normal appearances.",
      "🧠 Chainsaw Man explores human desire deeply.",
  
      "💀 Denji’s story is about finding meaning in suffering.",
      "🖤 The world is cruel but realistic.",
      "❤️ Hope exists in small forms.",
      "😈 Control vs freedom is the central conflict.",
      "🧠 The series reflects human fears and desires.",
    ],
  
    "Solo Leveling": [
      "💀 Sung Jin-Woo started as the weakest hunter in the world.",
      "🖤 Dungeons are deadly traps disguised as opportunities.",
      "❤️ Jin-Woo fights to protect his family above all.",
      "😈 The System treats him like a player in a game.",
      "🧠 Leveling up gives him power beyond normal limits.",
  
      "💀 Jin-Woo dies and is reborn as a player.",
      "🖤 Hunters risk death every time they enter a dungeon.",
      "❤️ His motivation comes from his mother’s illness.",
      "😈 The System has its own hidden purpose.",
      "🧠 Quests force him into dangerous situations.",
  
      "💀 Jin-Woo’s growth is faster than anyone else’s.",
      "🖤 Strong hunters dominate the weak.",
      "❤️ He values loyalty over power.",
      "😈 Shadow soldiers obey him absolutely.",
      "🧠 Experience points define his strength.",
  
      "💀 He fights alone to grow stronger.",
      "🖤 Double dungeons reveal hidden horrors.",
      "❤️ He protects those who cannot fight.",
      "😈 The System punishes failure harshly.",
      "🧠 Skills unlock through progression.",
  
      "💀 Jin-Woo’s power isolates him from others.",
      "🖤 Death is common in hunter society.",
      "❤️ His humanity remains despite power.",
      "😈 The Shadow Monarch controls death itself.",
      "🧠 Stats increase like a game character.",
  
      "💀 Jin-Woo commands an army of shadows.",
      "🖤 Monarchs aim to destroy humanity.",
      "❤️ He builds bonds with his allies.",
      "😈 Antares represents ultimate destruction.",
      "🧠 Shadow extraction turns enemies into soldiers.",
  
      "💀 His enemies become his strength after death.",
      "🖤 The world hides truths about hunters.",
      "❤️ His sister is his emotional anchor.",
      "😈 Monarch war threatens existence.",
      "🧠 Power scaling grows exponentially.",
  
      "💀 Jin-Woo becomes feared by both enemies and allies.",
      "🖤 S-rank hunters are rare but still vulnerable.",
      "❤️ Trust is earned through actions.",
      "😈 The System manipulates his growth.",
      "🧠 Cooldowns limit abilities strategically.",
  
      "💀 He surpasses human limits entirely.",
      "🖤 Dungeons can break without warning.",
      "❤️ He never forgets his weak past.",
      "😈 Rulers oppose Monarchs in hidden war.",
      "🧠 Equipment boosts stats significantly.",
  
      "💀 Jin-Woo’s calmness hides overwhelming power.",
      "🖤 Fear drives many hunters’ decisions.",
      "❤️ He fights for survival and protection.",
      "😈 The final battle decides humanity’s fate.",
      "🧠 Strategy is key even with power.",
  
      "💀 His journey is about evolution.",
      "🖤 Weakness is punished brutally.",
      "❤️ Loyalty defines his army.",
      "😈 Monarchs seek domination.",
      "🧠 Abilities grow through combat.",
  
      "💀 Jin-Woo becomes stronger than nations.",
      "🖤 Governments depend on hunters.",
      "❤️ Bonds keep him grounded.",
      "😈 Enemies fear his name.",
      "🧠 Data and stats define progression.",
  
      "💀 He turns despair into strength.",
      "🖤 Many hunters die unnoticed.",
      "❤️ Protecting loved ones drives him.",
      "😈 Power comes with responsibility.",
      "🧠 The System evolves with him.",
  
      "💀 Jin-Woo fights against fate itself.",
      "🖤 Darkness surrounds his journey.",
      "❤️ Hope remains through struggle.",
      "😈 Monarchs represent chaos.",
      "🧠 Skills combine for unique strategies.",
  
      "💀 He becomes the strongest existence.",
      "🖤 Humanity is fragile in this world.",
      "❤️ Family is his core motivation.",
      "😈 The war between Monarchs and Rulers shapes reality.",
      "🧠 Growth never truly stops.",
  
      "💀 Jin-Woo controls life and death.",
      "🖤 The battlefield is unforgiving.",
      "❤️ Trust builds his empire.",
      "😈 Final enemies test absolute limits.",
      "🧠 Intelligence enhances power usage.",
  
      "💀 His story is about rising from nothing.",
      "🖤 The world fears what it cannot control.",
      "❤️ Strength is used to protect, not destroy.",
      "😈 Destiny is rewritten through power.",
      "🧠 Solo Leveling blends game mechanics with reality.",
    ],
  
    "Blue Lock": [
      "💀 Yoichi Isagi’s greatest weapon is his ability to adapt instantly.",
      "🖤 Blue Lock destroys teamwork to create ultimate egoists.",
      "❤️ Isagi learns to trust others only when it leads to victory.",
      "😈 Jinpachi Ego believes selfishness creates the best striker.",
      "🧠 Spatial awareness is Isagi’s core skill.",
  
      "💀 Losing in Blue Lock means losing your football career forever.",
      "🖤 Players are treated as tools to build the perfect striker.",
      "❤️ Bachira Meguru seeks someone who understands his play.",
      "😈 Ego manipulates players psychologically.",
      "🧠 Vision and positioning matter more than raw strength.",
  
      "💀 Isagi evolves every time he faces defeat.",
      "🖤 The system eliminates the weak without hesitation.",
      "❤️ Friendships exist but are overshadowed by rivalry.",
      "😈 Players must devour each other’s abilities.",
      "🧠 Flow state unlocks peak performance.",
  
      "💀 Ego is treated as a weapon, not a flaw.",
      "🖤 The pressure breaks many talented players.",
      "❤️ Nagi Seishiro discovers passion through competition.",
      "😈 Winning matters more than fairness.",
      "🧠 Decision-making speed defines success.",
  
      "💀 Isagi turns weaknesses into strengths.",
      "🖤 Failure is constant in Blue Lock.",
      "❤️ Reo Mikage’s loyalty clashes with ambition.",
      "😈 Only one striker can stand at the top.",
      "🧠 Game IQ is more valuable than talent.",
  
      "💀 Each match reshapes players’ identities.",
      "🖤 Blue Lock isolates players from normal life.",
      "❤️ Bachira’s loneliness drives his creativity.",
      "😈 Ego’s philosophy rejects traditional teamwork.",
      "🧠 Predicting movements gives a major advantage.",
  
      "💀 Isagi’s growth is based on understanding others.",
      "🖤 The environment forces selfish decisions.",
      "❤️ Rivalries push players beyond limits.",
      "😈 Players must crush others’ dreams to succeed.",
      "🧠 Awareness of the entire field is key.",
  
      "💀 Scoring goals defines worth in Blue Lock.",
      "🖤 Emotions are often suppressed for victory.",
      "❤️ Nagi learns effort for the first time.",
      "😈 Ego designs matches to create conflict.",
      "🧠 Adaptability beats fixed talent.",
  
      "💀 Isagi constantly reinvents his playstyle.",
      "🖤 Trust is temporary in competition.",
      "❤️ Bonds are formed through shared struggle.",
      "😈 Players evolve by stealing ideas.",
      "🧠 Analysis during play is critical.",
  
      "💀 Every goal changes the hierarchy.",
      "🖤 Pressure reveals true ability.",
      "❤️ Reo struggles between control and freedom.",
      "😈 Ego values results over morality.",
      "🧠 Positioning creates scoring opportunities.",
  
      "💀 Isagi learns to think several steps ahead.",
      "🖤 Many players lose confidence under pressure.",
      "❤️ Bachira plays for joy, not just victory.",
      "😈 Blue Lock is a psychological experiment.",
      "🧠 Vision becomes a weapon.",
  
      "💀 Defeat leads to rapid growth.",
      "🖤 Competition creates constant tension.",
      "❤️ Nagi’s curiosity drives improvement.",
      "😈 Ego reshapes players’ personalities.",
      "🧠 Tactical awareness wins matches.",
  
      "💀 Isagi thrives in chaos.",
      "🖤 Players must abandon comfort zones.",
      "❤️ Rivalries evolve into respect.",
      "😈 Only the strongest mindset survives.",
      "🧠 Reading opponents is crucial.",
  
      "💀 Blue Lock turns players into predators.",
      "🖤 Weakness is exposed instantly.",
      "❤️ Teamwork exists only when beneficial.",
      "😈 Ego breaks traditional football values.",
      "🧠 Strategy determines outcomes.",
  
      "💀 Isagi becomes the center of the field.",
      "🖤 The system forces individuality.",
      "❤️ Players find purpose through competition.",
      "😈 Blue Lock creates monsters, not teammates.",
      "🧠 Intelligence shapes playstyle.",
  
      "💀 Every match is a battle of egos.",
      "🖤 Fear of failure drives performance.",
      "❤️ Passion fuels improvement.",
      "😈 Ego’s vision reshapes Japanese football.",
      "🧠 Skills evolve under pressure.",
  
      "💀 Isagi’s journey is about self-discovery.",
      "🖤 The environment is unforgiving.",
      "❤️ Growth comes from struggle.",
      "😈 Only one can become the best striker.",
      "🧠 Blue Lock blends psychology with sports.",
    ],
  
    "Hunter X Hunter": [
      "💀 Gon Freecss’s innocence hides a dangerously obsessive nature.",
      "🖤 The Hunter world is far darker than it appears.",
      "❤️ Gon values friendship more than morality.",
      "😈 Hisoka Morow fights only for his own twisted pleasure.",
      "🧠 Nen is one of the most complex power systems in anime.",
  
      "💀 Gon’s anger can override his sense of right and wrong.",
      "🖤 The Hunter Exam eliminates people without hesitation.",
      "❤️ Killua Zoldyck learns friendship through Gon.",
      "😈 Hisoka sees potential as something to cultivate then destroy.",
      "🧠 Nen categories define a user’s abilities.",
  
      "💀 Gon sacrifices everything for revenge against Pitou.",
      "🖤 The Zoldyck family trains children as assassins.",
      "❤️ Killua chooses Gon over his family.",
      "😈 The Phantom Troupe operates outside morality.",
      "🧠 Nen contracts can drastically increase power.",
  
      "💀 Gon’s transformation against Neferpitou is self-destruction.",
      "🖤 Chimera Ants blur the line between human and monster.",
      "❤️ Komugi changes Meruem’s understanding of humanity.",
      "😈 Meruem evolves beyond his original purpose.",
      "🧠 Aura control defines Nen mastery.",
  
      "💀 Gon loses his humanity in pursuit of revenge.",
      "🖤 The Chimera Ant arc shows the cruelty of nature.",
      "❤️ Killua protects Gon even from himself.",
      "😈 Meruem begins as a tyrant but becomes human-like.",
      "🧠 Nen abilities reflect personality deeply.",
  
      "💀 Gon’s strength comes from emotional extremes.",
      "🖤 Hunters often operate without moral limits.",
      "❤️ Friendship shapes the story more than power.",
      "😈 Hisoka enjoys chaos and unpredictability.",
      "🧠 Advanced Nen techniques require deep understanding.",
  
      "💀 Killua struggles to break free from his assassin instincts.",
      "🖤 The world rewards power over kindness.",
      "❤️ Alluka Zoldyck’s love is unconditional.",
      "😈 Nanika’s power comes with terrifying conditions.",
      "🧠 Conditions and restrictions make Nen stronger.",
  
      "💀 Gon’s journey is about losing innocence.",
      "🖤 Many characters face brutal realities early.",
      "❤️ Leorio fights to become a doctor for others.",
      "😈 The Phantom Troupe values loyalty within chaos.",
      "🧠 Nen battles are strategic, not just physical.",
  
      "💀 Gon often ignores consequences of his actions.",
      "🖤 The Hunter Association hides political conflict.",
      "❤️ Kurapika’s goal is driven by loss.",
      "😈 Kurapika risks everything for revenge.",
      "🧠 Chain Jail works only on Phantom Troupe members.",
  
      "💀 Kurapika sacrifices his lifespan for power.",
      "🖤 Revenge consumes his identity.",
      "❤️ Bonds are tested under extreme situations.",
      "😈 The Scarlet Eyes represent both beauty and tragedy.",
      "🧠 Specialist Nen users break normal rules.",
  
      "💀 Gon’s morality is flexible, not fixed.",
      "🖤 The world is unpredictable and harsh.",
      "❤️ Killua’s growth is emotional, not just physical.",
      "😈 Hisoka respects strength above all.",
      "🧠 Nen can be tailored to any concept.",
  
      "💀 Meruem’s death is peaceful despite his past.",
      "🖤 Power does not guarantee happiness.",
      "❤️ Komugi remains kind until the end.",
      "😈 The King learns humanity too late.",
      "🧠 Nen reflects inner desires.",
  
      "💀 Gon’s actions have lasting consequences.",
      "🖤 The strongest often feel empty.",
      "❤️ Killua chooses his own path.",
      "😈 Hisoka sees Gon as his future challenge.",
      "🧠 Nen mastery takes years to perfect.",
  
      "💀 Every arc explores different aspects of humanity.",
      "🖤 Darkness exists in every character.",
      "❤️ Friendship gives meaning to survival.",
      "😈 Villains often have understandable motives.",
      "🧠 Strategy decides most battles.",
  
      "💀 Gon represents potential taken too far.",
      "🖤 The world is morally grey.",
      "❤️ Bonds keep characters grounded.",
      "😈 Power always comes with cost.",
      "🧠 Nen is limited only by imagination.",
  
      "💀 Gon’s story is not purely heroic.",
      "🖤 Loss shapes every major character.",
      "❤️ Kindness exists even in darkness.",
      "😈 Obsession leads to destruction.",
      "🧠 Hunter x Hunter blends philosophy with action.",
  
      "💀 True strength is understanding oneself.",
      "🖤 The journey is more important than the goal.",
      "❤️ Growth comes through pain and connection.",
      "😈 Every character walks their own path.",
      "🧠 The series challenges traditional hero narratives.",
    ],
  
    "Assassination Classroom": [
      "💀 Koro-sensei teaches students how to kill him while helping them live better lives.",
      "🖤 Class 3-E is treated as outcasts by the entire school.",
      "❤️ Koro-sensei cares deeply for every student despite being their target.",
      "😈 The government sees Koro-sensei only as a threat to eliminate.",
      "🧠 His Mach 20 speed makes him nearly impossible to kill.",
  
      "💀 Students are trained as assassins at a young age.",
      "🖤 The education system labels students as failures permanently.",
      "❤️ Nagisa Shiota learns confidence through assassination training.",
      "😈 Killing Koro-sensei is tied to saving the Earth.",
      "🧠 Each student develops unique assassination skills.",
  
      "💀 Koro-sensei was once human before becoming a monster.",
      "🖤 His past is filled with violence and experimentation.",
      "❤️ He becomes the best teacher his students ever had.",
      "😈 His transformation is linked to world-ending power.",
      "🧠 Weaknesses are hidden within his abilities.",
  
      "💀 Nagisa’s calm nature hides deadly potential.",
      "🖤 Assassination becomes part of daily school life.",
      "❤️ Karma Akabane grows through rivalry and respect.",
      "😈 The mission forces students to question morality.",
      "🧠 Strategy is more important than strength.",
  
      "💀 Koro-sensei’s smile hides deep regret.",
      "🖤 The students face pressure from both school and mission.",
      "❤️ Bonds form through shared danger.",
      "😈 Failure means losing both money and purpose.",
      "🧠 Assassination techniques evolve over time.",
  
      "💀 Students learn life lessons through killing attempts.",
      "🖤 Society treats Class 3-E as disposable.",
      "❤️ Friendship becomes their greatest strength.",
      "😈 Teachers compete to eliminate Koro-sensei.",
      "🧠 Planning determines success in assassination.",
  
      "💀 Koro-sensei never harms his students despite the mission.",
      "🖤 His existence is seen as a global threat.",
      "❤️ He supports every student’s future.",
      "😈 The government hides the truth from the public.",
      "🧠 Each failure teaches new tactics.",
  
      "💀 Nagisa’s true strength is observation.",
      "🖤 Many adults underestimate the students.",
      "❤️ Koro-sensei believes in second chances.",
      "😈 The mission deadline creates constant tension.",
      "🧠 Understanding the target is key.",
  
      "💀 Karma’s intelligence makes him unpredictable.",
      "🖤 Violence is used as education.",
      "❤️ Students begin to care about their target.",
      "😈 Killing Koro-sensei becomes emotionally difficult.",
      "🧠 Adaptability improves survival.",
  
      "💀 Koro-sensei’s teaching changes their lives permanently.",
      "🖤 The system tries to keep them at the bottom.",
      "❤️ Class 3-E supports each other unconditionally.",
      "😈 The mission challenges their humanity.",
      "🧠 Teamwork increases success rate.",
  
      "💀 Students balance school life with assassination.",
      "🖤 The world outside ignores their struggle.",
      "❤️ Koro-sensei teaches beyond academics.",
      "😈 Hidden enemies complicate the mission.",
      "🧠 Skills develop through practice.",
  
      "💀 Nagisa questions what it means to kill.",
      "🖤 The line between teacher and target blurs.",
      "❤️ Koro-sensei protects them from harm.",
      "😈 The final decision carries emotional weight.",
      "🧠 Psychological tactics play a major role.",
  
      "💀 Each student grows beyond expectations.",
      "🖤 Failure is part of learning.",
      "❤️ Bonds make them stronger.",
      "😈 The truth about Koro-sensei changes everything.",
      "🧠 Knowledge is their greatest weapon.",
  
      "💀 Koro-sensei’s past defines his present.",
      "🖤 The mission reveals harsh realities.",
      "❤️ Students learn to value life.",
      "😈 Killing him may not be the right choice.",
      "🧠 Understanding emotions aids strategy.",
  
      "💀 The story blends comedy with tragedy.",
      "🖤 Death is always near.",
      "❤️ Love exists even in assassination.",
      "😈 The mission tests their morals.",
      "🧠 Growth comes through challenges.",
  
      "💀 Koro-sensei represents redemption.",
      "🖤 Society underestimates the weak.",
      "❤️ Students find purpose through him.",
      "😈 The ending forces an impossible choice.",
      "🧠 True strength is mental, not physical.",
  
      "💀 Their journey is about becoming better humans.",
      "🖤 The system tries to define their limits.",
      "❤️ Koro-sensei changes their future forever.",
      "😈 The mission is bigger than it seems.",
      "🧠 Assassination Classroom mixes philosophy with action.",
    ],
  
    "My Hero Academia": [
      "💀 Izuku Midoriya was born powerless in a world of superpowers.",
      "🖤 Society values quirks over character.",
      "❤️ All Might becomes Deku’s symbol of hope and mentorship.",
      "😈 All For One manipulates people like chess pieces.",
      "🧠 One For All stores power across generations.",
  
      "💀 Deku breaks his body to prove his worth.",
      "🖤 Heroes are treated as public figures, not just protectors.",
      "❤️ Uraraka Ochaco fights to support her family.",
      "😈 Shigaraki Tomura is shaped by neglect and hatred.",
      "🧠 Quirks evolve beyond their original limits.",
  
      "💀 Deku inherits power but must earn control.",
      "🖤 Villains are often products of society’s failure.",
      "❤️ Bakugo Katsuki hides respect behind aggression.",
      "😈 The League of Villains challenges hero society.",
      "🧠 Each quirk has strengths and weaknesses.",
  
      "💀 Deku’s analysis ability is his hidden strength.",
      "🖤 Hero society ignores those who don’t fit in.",
      "❤️ Todoroki Shoto struggles between family and identity.",
      "😈 All For One represents ultimate control.",
      "🧠 Training pushes quirks to new levels.",
  
      "💀 Deku’s journey is about self-worth.",
      "🖤 Power imbalance creates inequality.",
      "❤️ Class 1-A supports each other through danger.",
      "😈 Villains aim to destroy the system itself.",
      "🧠 Strategy is key in battles.",
  
      "💀 Deku learns from every failure.",
      "🖤 Being quirkless is seen as weakness.",
      "❤️ All Might sacrifices everything for peace.",
      "😈 Shigaraki seeks destruction without limits.",
      "🧠 One For All users share their will.",
  
      "💀 Deku’s strength comes from determination.",
      "🖤 The system creates both heroes and villains.",
      "❤️ Friendship gives students courage.",
      "😈 Villains exploit weaknesses in society.",
      "🧠 Combat training builds experience.",
  
      "💀 Deku risks his life constantly.",
      "🖤 Hero rankings create competition.",
      "❤️ Iida Tenya values justice deeply.",
      "😈 Stain questions what it means to be a true hero.",
      "🧠 Quirks reflect personality.",
  
      "💀 Deku carries the burden of expectations.",
      "🖤 Society depends heavily on heroes.",
      "❤️ Todoroki learns to accept himself.",
      "😈 Dabi reveals hidden truths.",
      "🧠 Power control defines effectiveness.",
  
      "💀 Deku’s growth is both physical and emotional.",
      "🖤 Many heroes struggle with responsibility.",
      "❤️ Uraraka grows stronger through determination.",
      "😈 The villain world mirrors hero society.",
      "🧠 Each battle teaches new techniques.",
  
      "💀 Deku never gives up despite fear.",
      "🖤 Weakness is judged harshly.",
      "❤️ Class bonds become family.",
      "😈 All For One plans far ahead.",
      "🧠 Knowledge improves combat ability.",
  
      "💀 Deku represents hope in a flawed system.",
      "🖤 Society hides its darker side.",
      "❤️ All Might inspires future heroes.",
      "😈 Shigaraki evolves into a major threat.",
      "🧠 Quirk combinations increase power.",
  
      "💀 Deku’s journey is about becoming a true hero.",
      "🖤 The world is not as simple as good vs evil.",
      "❤️ Friends support each other’s growth.",
      "😈 Villains believe they are justified.",
      "🧠 Skills develop through experience.",
  
      "💀 Every arc tests Deku’s resolve.",
      "🖤 Pressure affects even the strongest.",
      "❤️ Bonds create strength.",
      "😈 Power corrupts those who seek control.",
      "🧠 Strategy determines victory.",
  
      "💀 Deku continues despite injuries.",
      "🖤 The system needs change.",
      "❤️ Kindness defines true heroes.",
      "😈 The future holds greater conflicts.",
      "🧠 Growth never stops.",
  
      "💀 Deku rises from nothing to greatness.",
      "🖤 Society fears what it cannot control.",
      "❤️ Hope drives every hero forward.",
      "😈 Villains challenge the meaning of heroism.",
      "🧠 My Hero Academia blends action with philosophy.",
    ],
  
    "Death Note": [
      "💀 Light Yagami’s justice slowly turns into absolute tyranny.",
      "🖤 The Death Note corrupts anyone who uses it.",
      "❤️ Light believes he’s creating a better world.",
      "😈 Ryuk drops the Death Note out of boredom, not purpose.",
      "🧠 Writing a name requires both face and identity.",
  
      "💀 Light starts as a genius student but becomes a mass killer.",
      "🖤 Power without accountability leads to corruption.",
      "❤️ Misa Amane loves Light blindly despite his manipulation.",
      "😈 Shinigami view humans as entertainment.",
      "🧠 The Death Note has strict rules governing its use.",
  
      "💀 Light sacrifices morality for control.",
      "🖤 Innocent people die in pursuit of justice.",
      "❤️ L respects Light as his greatest rival.",
      "😈 Shinigami eyes trade lifespan for vision.",
      "🧠 Time of death can be controlled within limits.",
  
      "💀 Light isolates himself as Kira.",
      "🖤 Trust becomes impossible in a world of suspicion.",
      "❤️ Misa sacrifices years of her life for love.",
      "😈 Ryuk remains neutral, watching events unfold.",
      "🧠 Death Note users cannot go to heaven or hell.",
  
      "💀 Light’s intelligence becomes his weapon.",
      "🖤 The line between justice and evil disappears.",
      "❤️ L’s actions show subtle care for humanity.",
      "😈 Fake rules can manipulate investigations.",
      "🧠 Cause of death can be specified in detail.",
  
      "💀 Light believes he is the god of a new world.",
      "🖤 Fear controls society under Kira.",
      "❤️ Misa values love over logic.",
      "😈 Shinigami extend their lives by taking human lives.",
      "🧠 Memory loss removes all connection to the Death Note.",
  
      "💀 Light’s downfall begins with overconfidence.",
      "🖤 Even geniuses make fatal mistakes.",
      "❤️ L sacrifices himself to solve the case.",
      "😈 Near and M represent different approaches to justice.",
      "🧠 Ownership of the Death Note can be transferred.",
  
      "💀 Light manipulates everyone around him.",
      "🖤 The world becomes divided over Kira’s actions.",
      "❤️ Misa remains loyal despite being used.",
      "😈 Shinigami cannot be killed easily.",
      "🧠 Multiple Death Notes can exist at once.",
  
      "💀 Light’s justice ignores individual lives.",
      "🖤 Society fears unseen judgment.",
      "❤️ Human emotions drive critical decisions.",
      "😈 Ryuk only cares about amusement.",
      "🧠 Rules can be exploited strategically.",
  
      "💀 Light’s plan spans years of manipulation.",
      "🖤 The investigation creates constant paranoia.",
      "❤️ L’s quirks hide a brilliant mind.",
      "😈 Kira becomes a symbol rather than a person.",
      "🧠 Names written incorrectly have no effect.",
  
      "💀 Light loses his original ideals over time.",
      "🖤 Absolute power leads to isolation.",
      "❤️ Misa’s devotion blinds her judgment.",
      "😈 The Death Note influences human behavior.",
      "🧠 Shinigami can drop multiple notebooks.",
  
      "💀 Light’s downfall is inevitable from his path.",
      "🖤 Justice becomes subjective.",
      "❤️ L values truth over victory.",
      "😈 Near defeats Light through patience.",
      "🧠 Evidence and logic drive the story.",
  
      "💀 Light becomes what he once hated.",
      "🖤 Innocence is lost in pursuit of control.",
      "❤️ Human connections weaken under suspicion.",
      "😈 Power struggles define the narrative.",
      "🧠 Psychological battles replace physical fights.",
  
      "💀 Light’s final moments reveal his true self.",
      "🖤 Fear replaces confidence at the end.",
      "❤️ L’s legacy continues through Near.",
      "😈 Ryuk writes Light’s name in the end.",
      "🧠 Death Note rules remain consistent throughout.",
  
      "💀 Light’s story is a tragedy of ambition.",
      "🖤 The world changes under Kira’s rule.",
      "❤️ Love is used as a tool and weakness.",
      "😈 The Death Note tests human morality.",
      "🧠 Strategy determines every move.",
  
      "💀 Intelligence alone cannot guarantee victory.",
      "🖤 Darkness exists within human nature.",
      "❤️ Emotions influence even the smartest minds.",
      "😈 The notebook becomes a symbol of power.",
      "🧠 Death Note blends logic with philosophy.",
  
      "💀 Light’s journey is about losing humanity.",
      "🖤 The line between hero and villain disappears.",
      "❤️ Even flawed people seek justice.",
      "😈 Power reveals true intentions.",
      "🧠 The story is a battle of minds, not strength.",
    ],
  
    "Blue Box": [
      "💀 Taiki Inomata’s growth comes from quiet persistence, not talent.",
      "🖤 Competition constantly tests self-worth.",
      "❤️ Chinatsu Kano inspires Taiki without even trying.",
      "😈 Rivalry quietly drives emotional tension.",
      "🧠 Sports discipline reflects personal growth.",
  
      "💀 Taiki improves through consistent effort daily.",
      "🖤 Losing feels heavier when expectations rise.",
      "❤️ Living together deepens unspoken feelings.",
      "😈 Emotional distance creates inner conflict.",
      "🧠 Small habits build long-term success.",
  
      "💀 Taiki’s determination is his greatest strength.",
      "🖤 Pressure builds silently in competitive sports.",
      "❤️ Chinatsu hides her feelings behind focus.",
      "😈 Timing often works against emotions.",
      "🧠 Practice matters more than natural skill.",
  
      "💀 Growth is slow but meaningful.",
      "🖤 Failure shapes stronger resolve.",
      "❤️ Love develops through everyday moments.",
      "😈 Confession becomes harder with time.",
      "🧠 Consistency beats bursts of effort.",
  
      "💀 Taiki struggles between feelings and ambition.",
      "🖤 Doubt appears even in strong moments.",
      "❤️ Chinatsu motivates without words.",
      "😈 Emotional hesitation delays progress.",
      "🧠 Focus defines improvement.",
  
      "💀 Every match reflects internal struggle.",
      "🖤 Competition creates invisible pressure.",
      "❤️ Support builds confidence.",
      "😈 Silence hides true emotions.",
      "🧠 Routine creates discipline.",
  
      "💀 Taiki’s journey is about self-improvement.",
      "🖤 Expectations create fear of failure.",
      "❤️ Simple interactions hold deep meaning.",
      "😈 Misunderstandings create tension.",
      "🧠 Training builds both body and mind.",
  
      "💀 Effort often goes unnoticed.",
      "🖤 Loss teaches more than victory.",
      "❤️ Shared space strengthens bonds.",
      "😈 Feelings remain unspoken.",
      "🧠 Patience is key to growth.",
  
      "💀 Taiki faces stronger opponents constantly.",
      "🖤 Comparison affects confidence.",
      "❤️ Chinatsu’s presence brings comfort.",
      "😈 Distance increases emotional struggle.",
      "🧠 Improvement requires reflection.",
  
      "💀 Small progress leads to big change.",
      "🖤 Setbacks test determination.",
      "❤️ Emotional support matters more than skill.",
      "😈 Fear of rejection holds him back.",
      "🧠 Strategy improves performance.",
  
      "💀 Taiki’s strength is consistency.",
      "🖤 Pressure builds internally.",
      "❤️ Love grows slowly but deeply.",
      "😈 Timing affects outcomes.",
      "🧠 Focus improves results.",
  
      "💀 Every practice matters.",
      "🖤 Doubt challenges confidence.",
      "❤️ Encouragement drives growth.",
      "😈 Hesitation delays success.",
      "🧠 Discipline shapes character.",
  
      "💀 Taiki learns through failure.",
      "🖤 Competition creates stress.",
      "❤️ Bonds deepen over time.",
      "😈 Emotions complicate decisions.",
      "🧠 Effort builds skill.",
  
      "💀 Progress takes time.",
      "🖤 Expectations create pressure.",
      "❤️ Small moments build connection.",
      "😈 Silence creates misunderstanding.",
      "🧠 Improvement is gradual.",
  
      "💀 Taiki balances love and ambition.",
      "🖤 Internal conflict drives growth.",
      "❤️ Chinatsu inspires silently.",
      "😈 Emotional distance creates tension.",
      "🧠 Hard work beats talent.",
  
      "💀 Every challenge builds strength.",
      "🖤 Fear of failure is constant.",
      "❤️ Support creates motivation.",
      "😈 Feelings remain hidden.",
      "🧠 Focus drives success.",
  
      "💀 Taiki’s journey is realistic and grounded.",
      "🖤 Pressure never fully disappears.",
      "❤️ Love grows naturally.",
      "😈 Timing shapes everything.",
      "🧠 Growth comes step by step.",
    ],
  
    Kingdom: [
      "💀 Xin fights to rise from a slave to the greatest general under the heavens.",
      "🖤 War in ancient China is brutal and unforgiving.",
      "❤️ Xin values loyalty and brotherhood above all.",
      "😈 Ei Sei aims to unify China through absolute power.",
      "🧠 Strategy decides battles more than strength.",
  
      "💀 Xin’s dream is built on endless battlefield deaths.",
      "🖤 Soldiers are treated as expendable tools.",
      "❤️ Piao’s sacrifice becomes Xin’s driving force.",
      "😈 Kings manipulate war for political gain.",
      "🧠 Generals control battles like chess.",
  
      "💀 Xin grows stronger through real combat, not training.",
      "🖤 The battlefield shows humanity’s darkest side.",
      "❤️ Ei Sei trusts Xin beyond status.",
      "😈 Power struggles define kingdoms.",
      "🧠 Tactics can overcome larger armies.",
  
      "💀 Every victory comes with heavy loss.",
      "🖤 War destroys both enemies and allies.",
      "❤️ Bonds between soldiers create unity.",
      "😈 Ambition leads to betrayal.",
      "🧠 Terrain plays a crucial role in strategy.",
  
      "💀 Xin’s strength comes from sheer willpower.",
      "🖤 Death is constant in war.",
      "❤️ Friendship drives soldiers forward.",
      "😈 Generals sacrifice lives for victory.",
      "🧠 Leadership determines morale.",
  
      "💀 Xin starts with nothing but determination.",
      "🖤 Weakness leads to death instantly.",
      "❤️ Trust between comrades is vital.",
      "😈 Political schemes shape wars.",
      "🧠 Timing is key in battle plans.",
  
      "💀 War forces rapid growth.",
      "🖤 Mercy is rare on the battlefield.",
      "❤️ Loyalty defines true warriors.",
      "😈 Betrayal changes outcomes instantly.",
      "🧠 Intelligence wins wars.",
  
      "💀 Xin fights stronger enemies constantly.",
      "🖤 Fear spreads quickly among troops.",
      "❤️ Brotherhood creates courage.",
      "😈 Kingdoms seek dominance at any cost.",
      "🧠 Strategy adapts during battle.",
  
      "💀 Strength alone cannot win wars.",
      "🖤 Soldiers face death daily.",
      "❤️ Leaders inspire their armies.",
      "😈 Power corrupts rulers.",
      "🧠 Planning determines success.",
  
      "💀 Xin’s journey is about rising through ranks.",
      "🖤 War leaves lasting scars.",
      "❤️ Comrades become family.",
      "😈 Enemies use deception.",
      "🧠 Adaptability is essential.",
  
      "💀 Each battle shapes Xin’s future.",
      "🖤 Survival is uncertain.",
      "❤️ Bonds create strength.",
      "😈 Generals compete for glory.",
      "🧠 Strategy evolves constantly.",
  
      "💀 Xin learns through hardship.",
      "🖤 The battlefield shows no mercy.",
      "❤️ Loyalty never fades.",
      "😈 Ambition drives conflict.",
      "🧠 Knowledge improves tactics.",
  
      "💀 War tests every limit.",
      "🖤 Death surrounds every soldier.",
      "❤️ Trust builds armies.",
      "😈 Deception wins battles.",
      "🧠 Leadership shapes outcomes.",
  
      "💀 Xin never gives up despite odds.",
      "🖤 War consumes lives endlessly.",
      "❤️ Friendship creates hope.",
      "😈 Power defines hierarchy.",
      "🧠 Strategy outweighs strength.",
  
      "💀 Every step forward costs lives.",
      "🖤 Darkness defines war.",
      "❤️ Bonds keep soldiers fighting.",
      "😈 Conflict never truly ends.",
      "🧠 Intelligence leads victory.",
  
      "💀 Xin’s story is about rising from nothing.",
      "🖤 War shapes nations.",
      "❤️ Loyalty defines greatness.",
      "😈 Kings pursue domination.",
      "🧠 Kingdom blends history with strategy.",
    ]
  };
  