// ==========================
// 📚 DATA
// ==========================
const mangaByGenre = {
    action: [
        { title: "Chainsaw Man", img: "./image/mangadenji.webp" },
        { title: "Jujutsu Kaisen", img: "./image/jjkmanga.webp" },
        { title: "Sakamoto Days", img: "./image/sakamotomanga.webp" },
        { title: "Attack on Titan", img: "./image/aot.webp" },
        { title: "Demon Slayer", img: "./image/demonslayer.webp" },
        { title: "Solo Leveling", img: "./image/mangasololevel.webp" },
        { title: "My Hero Academia", img: "./image/mha.webp" },
        { title: "Tokyo Revengers", img: "./image/tokyorevengers.webp" },
        { title: "Black Clover", img: "./image/blackclover.webp" },
        { title: "Fire Force", img: "./image/fireforce.webp" },
    
        { title: "One Piece", img: "./image/mangaonepiece.webp" },
        { title: "Naruto", img: "./image/naruto.webp" },
        { title: "Boruto", img: "./image/boruto.webp" },
        { title: "Bleach", img: "./image/bleach.webp" },
        { title: "Hunter x Hunter", img: "./image/hxh.webp" },
        { title: "Dragon Ball Super", img: "./image/dbs.webp" },
        { title: "Fullmetal Alchemist", img: "./image/fma.webp" },
        { title: "Mob Psycho 100", img: "./image/mobpsycho.webp" },
        { title: "Vinland Saga", img: "./image/vinland.webp" },
        { title: "Akame ga Kill", img: "./image/akame.webp" },
    
        { title: "Blue Exorcist", img: "./image/blueexorcist.webp" },
        { title: "Noragami", img: "./image/noragami.webp" },
        { title: "God of High School", img: "./image/goh.webp" },
        { title: "Tower of God", img: "./image/towerofgod.webp" },
        { title: "Seraph of the End", img: "./image/seraph.webp" },
        { title: "Parasyte", img: "./image/parasyte.webp" },
        { title: "Dororo", img: "./image/dororo.webp" },
        { title: "Kill la Kill", img: "./image/killlakill.webp" },
        { title: "Bungo Stray Dogs", img: "./image/bungo.webp" },
        { title: "Fate Stay Night", img: "./image/fate.webp" }
    ],

    adventure: [
        { title: "One Piece", img: "./image/mangaonepiece.webp" },
        { title: "Hunter x Hunter", img: "./image/hxh.webp" },
        { title: "Attack on Titan", img: "./image/aot.webp" },
        { title: "Fullmetal Alchemist", img: "./image/fma.webp" },
        { title: "Made in Abyss", img: "./image/madeinabyss.webp" },
        { title: "Magi", img: "./image/magi.webp" },
        { title: "Vinland Saga", img: "./image/vinland.webp" },
        { title: "Dr Stone", img: "./image/drstone.webp" },
        { title: "Naruto", img: "./image/naruto.webp" },
        { title: "Boruto", img: "./image/boruto.webp" },
    
        { title: "Black Clover", img: "./image/blackclover.webp" },
        { title: "Seven Deadly Sins", img: "./image/sds.webp" },
        { title: "Fairy Tail", img: "./image/fairytale.webp" },
        { title: "Sword Art Online", img: "./image/sao.webp" },
        { title: "Re Zero", img: "./image/rezero.webp" },
        { title: "That Time I Got Reincarnated as a Slime", img: "./image/slime.webp" },
        { title: "No Game No Life", img: "./image/ngnl.webp" },
        { title: "Log Horizon", img: "./image/loghorizon.webp" },
        { title: "Tower of God", img: "./image/towerofgod.webp" },
        { title: "God of High School", img: "./image/goh.webp" },
    
        { title: "Dororo", img: "./image/dororo.webp" },
        { title: "Akame ga Kill", img: "./image/akame.webp" },
        { title: "Blue Exorcist", img: "./image/blueexorcist.webp" },
        { title: "Noragami", img: "./image/noragami.webp" },
        { title: "Bungo Stray Dogs", img: "./image/bungo.webp" },
        { title: "Fate Stay Night", img: "./image/fate.webp" },
        { title: "Kino no Tabi", img: "./image/kino.webp" },
        { title: "The Rising of the Shield Hero", img: "./image/shieldhero.webp" },
        { title: "Spice and Wolf", img: "./image/spicewolf.webp" },
        { title: "Ranking of Kings", img: "./image/rankingofkings.webp" }
    ],

    dark: [
        { title: "Tokyo Ghoul", img: "./image/tokyoghoul.webp" },
        { title: "Attack on Titan", img: "./image/aot.webp" },
        { title: "Death Note", img: "./image/deathnote.webp" },
        { title: "Chainsaw Man", img: "./image/mangadenji.webp" },
        { title: "Jujutsu Kaisen", img: "./image/jjkmanga.webp" },
        { title: "Parasyte", img: "./image/parasyte.webp" },
        { title: "Devilman Crybaby", img: "./image/devilman.webp" },
        { title: "Akame ga Kill", img: "./image/akame.webp" },
        { title: "Dorohedoro", img: "./image/dorohedoro.webp" },
        { title: "Berserk", img: "./image/berserk.webp" },
    
        { title: "Vinland Saga", img: "./image/vinland.webp" },
        { title: "Hell's Paradise", img: "./image/hellsparadise.webp" },
        { title: "Dororo", img: "./image/dororo.webp" },
        { title: "Made in Abyss", img: "./image/madeinabyss.webp" },
        { title: "Re Zero", img: "./image/rezero.webp" },
        { title: "Future Diary", img: "./image/futurediary.webp" },
        { title: "Another", img: "./image/another.webp" },
        { title: "Erased", img: "./image/erased.webp" },
        { title: "Psycho Pass", img: "./image/psychopass.webp" },
        { title: "Monster", img: "./image/monster.webp" },
    
        { title: "Black Lagoon", img: "./image/blacklagoon.webp" },
        { title: "Elfen Lied", img: "./image/elfenlied.webp" },
        { title: "Hellsing Ultimate", img: "./image/hellsing.webp" },
        { title: "Claymore", img: "./image/claymore.webp" },
        { title: "Deadman Wonderland", img: "./image/deadman.webp" },
        { title: "Zankyou no Terror", img: "./image/terror.webp" },
        { title: "Goblin Slayer", img: "./image/goblinslayer.webp" },
        { title: "The Promised Neverland", img: "./image/neverland.webp" },
        { title: "Serial Experiments Lain", img: "./image/lain.webp" },
        { title: "Shiki", img: "./image/shiki.webp" }
    ],

    horror: [
        { title: "Junji Ito Collection", img: "./image/junjiito.webp" },
        { title: "Uzumaki", img: "./image/uzumaki.webp" },
        { title: "Tomie", img: "./image/tomie.webp" },
        { title: "Another", img: "./image/another.webp" },
        { title: "Tokyo Ghoul", img: "./image/tokyoghoul.webp" },
        { title: "Parasyte", img: "./image/parasyte.webp" },
        { title: "Shiki", img: "./image/shiki.webp" },
        { title: "The Promised Neverland", img: "./image/neverland.webp" },
        { title: "Devilman Crybaby", img: "./image/devilman.webp" },
        { title: "Dandadan", img: "./image/mangadendadan.webp" },
    
        { title: "Hell's Paradise", img: "./image/hellsparadise.webp" },
        { title: "Corpse Party", img: "./image/corpseparty.webp" },
        { title: "Higurashi When They Cry", img: "./image/higurashi.webp" },
        { title: "Elfen Lied", img: "./image/elfenlied.webp" },
        { title: "Deadman Wonderland", img: "./image/deadman.webp" },
        { title: "Blood C", img: "./image/bloodc.webp" },
        { title: "Highschool of the Dead", img: "./image/hotd.webp" },
        { title: "Kabaneri of the Iron Fortress", img: "./image/kabaneri.webp" },
        { title: "Yamishibai", img: "./image/yamishibai.webp" },
    
        { title: "Ghost Hunt", img: "./image/ghosthunt.webp" },
        { title: "Mononoke", img: "./image/mononoke.webp" },
        { title: "Boogiepop Phantom", img: "./image/boogiepop.webp" },
        { title: "Serial Experiments Lain", img: "./image/lain.webp" },
        { title: "Erased", img: "./image/erased.webp" },
        { title: "Perfect Blue", img: "./image/perfectblue.webp" },
        { title: "Paprika", img: "./image/paprika.webp" },
        { title: "Housing Complex C", img: "./image/housingc.webp" },
        { title: "Dark Gathering", img: "./image/darkgathering.webp" },
        { title: "Zom 100", img: "./image/zom100.webp" },
        { title: "Hell Girl", img: "./image/hellgirl.webp" }
    ],

    romance: [
        { title: "Blue Box", img: "./image/mangabluebox.webp" },
        { title: "Your Name", img: "./image/yourname.png" },
        { title: "Weathering With You", img: "./image/weathering.png" },
        { title: "Horimiya", img: "./image/horimiya.png" },
        { title: "Toradora", img: "./image/toradora.png" },
        { title: "Kaguya-sama Love is War", img: "./image/kaguya.png" },
        { title: "My Dress-Up Darling", img: "./image/dressup.png" },
        { title: "Rent a Girlfriend", img: "./image/rentgf.png" },
        { title: "Golden Time", img: "./image/goldentime.png" },
        { title: "Clannad", img: "./image/clannad.png" },
    
        { title: "Clannad After Story", img: "./image/clannad2.png" },
        { title: "Fruits Basket", img: "./image/fruitsbasket.png" },
        { title: "Ao Haru Ride", img: "./image/aoharu.png" },
        { title: "Lovely Complex", img: "./image/lovelycomplex.png" },
        { title: "Orange", img: "./image/orange.png" },
        { title: "ReLife", img: "./image/relife.png" },
        { title: "Tsuki ga Kirei", img: "./image/tsuki.png" },
        { title: "The Angel Next Door Spoils Me Rotten", img: "./image/angelnextdoor.png" },
        { title: "Say I Love You", img: "./image/sayiloveyou.png" },
        { title: "Domestic Girlfriend", img: "./image/domesticgf.png" },
    
        { title: "Nisekoi", img: "./image/nisekoi.png" },
        { title: "Oregairu", img: "./image/oregairu.png" },
        { title: "My Little Monster", img: "./image/mylittlemonster.png" },
        { title: "Snow White with the Red Hair", img: "./image/snowwhite.png" },
        { title: "Yamada-kun and the Seven Witches", img: "./image/yamada.png" },
        { title: "Wotakoi", img: "./image/wotakoi.png" },
        { title: "Insomniacs After School", img: "./image/insomniacs.png" },
        { title: "Skip and Loafer", img: "./image/skiploafer.png" },
        { title: "Kimi ni Todoke", img: "./image/kimitodoke.png" },
        { title: "I Want to Eat Your Pancreas", img: "./image/pancreas.png" }
    ],

    comedy: [
        { title: "Gintama", img: "./image/gintama.png" },
        { title: "One Punch Man", img: "./image/opm.png" },
        { title: "Mob Psycho 100", img: "./image/mobpsycho.png" },
        { title: "KonoSuba", img: "./image/konosuba.png" },
        { title: "The Disastrous Life of Saiki K", img: "./image/saiki.png" },
        { title: "Grand Blue", img: "./image/grandblue.png" },
        { title: "Nichijou", img: "./image/nichijou.png" },
        { title: "Asobi Asobase", img: "./image/asobi.png" },
        { title: "Prison School", img: "./image/prisonschool.png" },
        { title: "Daily Lives of High School Boys", img: "./image/dailylife.png" },
    
        { title: "Kaguya-sama Love is War", img: "./image/kaguya.png" },
        { title: "My Dress-Up Darling", img: "./image/dressup.png" },
        { title: "Wotakoi", img: "./image/wotakoi.png" },
        { title: "Horimiya", img: "./image/horimiya.png" },
        { title: "Toradora", img: "./image/toradora.png" },
        { title: "The Devil is a Part-Timer", img: "./image/devilisaparttimer.png" },
        { title: "Spy x Family", img: "./image/spyfamily.png" },
        { title: "Mashle", img: "./image/mashle.png" },
        { title: "Hinamatsuri", img: "./image/hinamatsuri.png" },
        { title: "Barakamon", img: "./image/barakamon.png" },
    
        { title: "Sket Dance", img: "./image/sketdance.png" },
        { title: "Beelzebub", img: "./image/beelzebub.png" },
        { title: "The Way of the Househusband", img: "./image/househusband.png" },
        { title: "My Little Monster", img: "./image/mylittlemonster.png" },
        { title: "School Rumble", img: "./image/schoolrumble.png" },
        { title: "Lucky Star", img: "./image/luckystar.png" },
        { title: "Azumanga Daioh", img: "./image/azumanga.png" },
        { title: "Konohana Kitan", img: "./image/konohana.png" },
        { title: "Romantic Killer", img: "./image/romantickiller.png" },
        { title: "Zom 100", img: "./image/zom100.png" }
    ],

    school: [
        { title: "Classroom of the Elite", img: "./image/classroom.png" },
        { title: "Horimiya", img: "./image/horimiya.png" },
        { title: "Toradora", img: "./image/toradora.png" },
        { title: "My Hero Academia", img: "./image/mha.png" },
        { title: "Assassination Classroom", img: "./image/assassination.png" },
        { title: "Blue Exorcist", img: "./image/blueexorcist.png" },
        { title: "Jujutsu Kaisen", img: "./image/jjkmanga.png" },
        { title: "Kaguya-sama Love is War", img: "./image/kaguya.png" },
        { title: "My Dress-Up Darling", img: "./image/dressup.png" },
        { title: "Rent a Girlfriend", img: "./image/rentgf.png" },
    
        { title: "Oregairu", img: "./image/oregairu.png" },
        { title: "Nisekoi", img: "./image/nisekoi.png" },
        { title: "The Quintessential Quintuplets", img: "./image/quintuplets.png" },
        { title: "Ao Haru Ride", img: "./image/aoharu.png" },
        { title: "Orange", img: "./image/orange.png" },
        { title: "ReLife", img: "./image/relife.png" },
        { title: "Tsuki ga Kirei", img: "./image/tsuki.png" },
        { title: "Komi Can't Communicate", img: "./image/komi.png" },
        { title: "My Little Monster", img: "./image/mylittlemonster.png" },
        { title: "Skip and Loafer", img: "./image/skiploafer.png" },
    
        { title: "Nichijou", img: "./image/nichijou.png" },
        { title: "Asobi Asobase", img: "./image/asobi.png" },
        { title: "Daily Lives of High School Boys", img: "./image/dailylife.png" },
        { title: "School Rumble", img: "./image/schoolrumble.png" },
        { title: "Lucky Star", img: "./image/luckystar.png" },
        { title: "Azumanga Daioh", img: "./image/azumanga.png" },
        { title: "Yamada-kun and the Seven Witches", img: "./image/yamada.png" },
        { title: "Angel Beats", img: "./image/angelbeats.png" },
        { title: "Charlotte", img: "./image/charlotte.png" },
        { title: "Food Wars", img: "./image/foodwars.png" }
    ],

    psychological: [
        { title: "Death Note", img: "./image/deathnote.png" },
        { title: "Monster", img: "./image/monster.png" },
        { title: "Code Geass", img: "./image/codegeass.png" },
        { title: "Psycho Pass", img: "./image/psychopass.png" },
        { title: "Erased", img: "./image/erased.png" },
        { title: "The Promised Neverland", img: "./image/neverland.png" },
        { title: "Parasyte", img: "./image/parasyte.png" },
        { title: "Tokyo Ghoul", img: "./image/tokyoghoul.png" },
        { title: "Serial Experiments Lain", img: "./image/lain.png" },
        { title: "Steins Gate", img: "./image/steinsgate.png" },
    
        { title: "Re Zero", img: "./image/rezero.png" },
        { title: "Future Diary", img: "./image/futurediary.png" },
        { title: "Another", img: "./image/another.png" },
        { title: "Perfect Blue", img: "./image/perfectblue.png" },
        { title: "Paprika", img: "./image/paprika.png" },
        { title: "Zankyou no Terror", img: "./image/terror.png" },
        { title: "Devilman Crybaby", img: "./image/devilman.png" },
        { title: "Berserk", img: "./image/berserk.png" },
        { title: "Made in Abyss", img: "./image/madeinabyss.png" },
        { title: "Shiki", img: "./image/shiki.png" },
    
        { title: "Welcome to the NHK", img: "./image/nhk.png" },
        { title: "Boogiepop Phantom", img: "./image/boogiepop.png" },
        { title: "Kaiji", img: "./image/kaiji.png" },
        { title: "Akagi", img: "./image/akagi.png" },
        { title: "Odd Taxi", img: "./image/oddtaxi.png" },
        { title: "Sonny Boy", img: "./image/sonnyboy.png" },
        { title: "Classroom of the Elite", img: "./image/classroom.png" },
        { title: "Tomodachi Game", img: "./image/tomodachi.png" },
        { title: "Paranoia Agent", img: "./image/paranoia.png" },
        { title: "Ghost in the Shell", img: "./image/gitss.png" }
    ],

    fantasy: [
        { title: "Solo Leveling", img: "./image/mangasololevel.png" },
        { title: "Black Clover", img: "./image/blackclover.png" },
        { title: "Fairy Tail", img: "./image/fairytail.png" },
        { title: "Magi", img: "./image/magi.png" },
        { title: "Seven Deadly Sins", img: "./image/sds.png" },
        { title: "Re Zero", img: "./image/rezero.png" },
        { title: "That Time I Got Reincarnated as a Slime", img: "./image/slime.png" },
        { title: "Sword Art Online", img: "./image/sao.png" },
        { title: "No Game No Life", img: "./image/ngnl.png" },
        { title: "Log Horizon", img: "./image/loghorizon.png" },
    
        { title: "Konosuba", img: "./image/konosuba.png" },
        { title: "Overlord", img: "./image/overlord.png" },
        { title: "Shield Hero", img: "./image/shieldhero.png" },
        { title: "DanMachi", img: "./image/danmachi.png" },
        { title: "Made in Abyss", img: "./image/madeinabyss.png" },
        { title: "Vinland Saga", img: "./image/vinland.png" },
        { title: "Attack on Titan", img: "./image/aot.png" },
        { title: "Fate Stay Night", img: "./image/fate.png" },
        { title: "Fate Zero", img: "./image/fatezero.png" },
        { title: "Akame ga Kill", img: "./image/akame.png" },
    
        { title: "Dororo", img: "./image/dororo.png" },
        { title: "Ranking of Kings", img: "./image/rankingofkings.png" },
        { title: "Spice and Wolf", img: "./image/spicewolf.png" },
        { title: "The Ancient Magus Bride", img: "./image/magusbride.png" },
        { title: "Grimgar", img: "./image/grimgar.png" },
        { title: "Goblin Slayer", img: "./image/goblinslayer.png" },
        { title: "Tower of God", img: "./image/towerofgod.png" },
        { title: "God of High School", img: "./image/goh.png" },
        { title: "Blue Exorcist", img: "./image/blueexorcist.png" },
        { title: "Kino no Tabi", img: "./image/kino.png" }
    ],

    "sci-fi": [
        { title: "Dr Stone", img: "./image/drstone.png" },
        { title: "Steins Gate", img: "./image/steinsgate.png" },
        { title: "Cyberpunk Edgerunners", img: "./image/cyberpunk.png" },
        { title: "Akira", img: "./image/akira.png" },
        { title: "Ghost in the Shell", img: "./image/gitss.png" },
        { title: "Neon Genesis Evangelion", img: "./image/evangelion.png" },
        { title: "Code Geass", img: "./image/codegeass.png" },
        { title: "Psycho Pass", img: "./image/psychopass.png" },
        { title: "Ergo Proxy", img: "./image/ergoproxy.png" },
        { title: "Serial Experiments Lain", img: "./image/lain.png" },
    
        { title: "Gurren Lagann", img: "./image/gurrenlagann.png" },
        { title: "Darling in the Franxx", img: "./image/franxx.png" },
        { title: "86 Eighty Six", img: "./image/86.png" },
        { title: "Astra Lost in Space", img: "./image/astra.png" },
        { title: "Space Dandy", img: "./image/spacedandy.png" },
        { title: "Cowboy Bebop", img: "./image/cowboybebop.png" },
        { title: "Trigun", img: "./image/trigun.png" },
        { title: "Planetes", img: "./image/planetes.png" },
        { title: "Blame", img: "./image/blame.png" },
        { title: "Knights of Sidonia", img: "./image/sidonia.png" },
    
        { title: "No Guns Life", img: "./image/nogunslife.png" },
        { title: "Vivy Fluorite Eye's Song", img: "./image/vivy.png" },
        { title: "Heavenly Delusion", img: "./image/heavenly.png" },
        { title: "Deca Dence", img: "./image/decadence.png" },
        { title: "Eden of the East", img: "./image/eden.png" },
        { title: "Dimension W", img: "./image/dimensionw.png" },
        { title: "Expelled from Paradise", img: "./image/expelled.png" },
        { title: "Aldnoah Zero", img: "./image/aldnoah.png" },
        { title: "Zegapain", img: "./image/zegapain.png" },
        { title: "Time of Eve", img: "./image/timeofeve.png" }
    ]
};
